[wagdie-subgraph] add: New vote weights if staked or seared.
snapshot-labs/snapshot-strategies pull request #1018
Opened 2023-01-23 17:50 UTC by LookingForOwls

Changes proposed in this pull request:
- Update vote calculations to give bonus to WAGDIE NFTs if staked or seared.

2023-01-23 17:57 UTC, ChaituVR commented
@IcculusHerEmissary can take a look?

2023-01-23 21:02 UTC, IcculusHerEmissary commented
@ChaituVR yes this change is correct and approved by us. Thank you for checking with me.

2023-01-23 21:06 UTC, IcculusHerEmissary approved these changes
- We requested this change from @LookingForOwls and it is functioning as expected.

2023-01-24 23:11 UTC, IcculusHerEmissary commented
Anything else I need to do for this PR?

2023-01-26 06:41 UTC, ChaituVR requested changes
Everything else looks good ✅ 
No open proposals ✅

2023-01-26 06:41 UTC, ChaituVR commented on src/strategies/wagdie-subgraph/index.ts
> +export const author = 'LookingForOwls';
```suggestion
export const author = 'IcculusHerEmissary';
```

2023-01-26 19:35 UTC, ChaituVR approved these changes

2023-01-26 19:36 UTC, merged