[rdnt-capital-dlp] added total dlp strategy
snapshot-labs/snapshot-strategies pull request #1109
Opened 2023-03-24 10:18 UTC by JDoy99

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2023-03-24 11:10 UTC, ChaituVR requested changes

2023-03-24 11:10 UTC, ChaituVR commented on src/strategies/rdnt-capital-dlp/index.ts
Hey @JDoy99 I think this can be achieved with `contract-call` strategy, you tried? let me know if you see any blocker

2023-03-24 11:20 UTC, JDoy99 commented on src/strategies/rdnt-capital-dlp/index.ts
Hi there @ChaituVR 

I have tested out this in ```contract-call``` but it doesn't work unfortunately. It only returns my total vesting RDNT token, rather than the dLP amount

This is an example of me testing in the playground
![telegram-cloud-photo-size-4-5832389546304715795-y](https://user-images.githubusercontent.com/103535732/227507691-297ed443-110e-402b-909a-43109489ca03.jpg)

This is the result of the strategy test however, which is correct as my test address has 462 dLP tokens.
![image](https://user-images.githubusercontent.com/103535732/227508076-f9f58f33-469f-4af6-8f53-6fa267d406f7.png)

2023-03-24 12:21 UTC, ChaituVR commented on src/strategies/rdnt-capital-dlp/index.ts
Try adding the `"output"` param or share the playground link here, i can try and let you know :)

2023-03-24 12:27 UTC, JDoy99 commented on src/strategies/rdnt-capital-dlp/index.ts
> Try adding the `"output"` param or share the playground link here, i can try and let you know :)

For some reason it wont let me add this into a new contract-call and save it.

Here is the code ```{
  "symbol": "dLP RDNT",
  "address": "0x76ba3eC5f5adBf1C58c91e86502232317EeA72dE",
  "decimals": 18,
  "methodABI": {
   {
    inputs: [
      {
        internalType: 'address',
        name: 'user',
        type: 'address'
      }
    ],
    name: 'lockedBalances',
    outputs: [
      {
        internalType: 'uint256',
        name: 'total',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'unlockable',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'locked',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'lockedWithMultiplier',
        type: 'uint256'
      },
      {
        components: [
          {
            internalType: 'uint256',
            name: 'amount',
            type: 'uint256'
          },
          {
            internalType: 'uint256',
            name: 'unlockTime',
            type: 'uint256'
          },
          {
            internalType: 'uint256',
            name: 'multiplier',
            type: 'uint256'
          },
          {
            internalType: 'uint256',
            name: 'duration',
            type: 'uint256'
          }
        ],
        internalType: 'struct LockedBalance[]',
        name: 'lockData',
        type: 'tuple[]'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  }
}```

2023-03-24 17:30 UTC, ChaituVR commented on src/strategies/rdnt-capital-dlp/index.ts
There is something wrong with the ABI format, i tried formating it for you and it is working fine here 
https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NzZiYTNlQzVmNWFkQmYxQzU4YzkxZTg2NTAyMjMyMzE3RWVBNzJkRSIsInN5bWJvbCI6ImRMUCBSRE5UIiwiZGVjaW1hbHMiOjE4LCJtZXRob2RBQkkiOnsiaW5wdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6InVzZXIiLCJ0eXBlIjoiYWRkcmVzcyJ9XSwibmFtZSI6ImxvY2tlZEJhbGFuY2VzIiwib3V0cHV0cyI6W3siaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJ0b3RhbCIsInR5cGUiOiJ1aW50MjU2In1dLCJzdGF0ZU11dGFiaWxpdHkiOiJ2aWV3IiwidHlwZSI6ImZ1bmN0aW9uIn0sIm91dHB1dCI6InRvdGFsIn0sIm5ldHdvcmsiOiI0MjE2MSIsInNuYXBzaG90IjoiNzMyNTA4NjMiLCJhZGRyZXNzZXMiOlsiMHgyZWFhNzMyN2U5YjVmZjQ2YmMyYjc0NTJhY2U5ZTQ0YTE1MjhlYjg0Il19


Params:
```JSON
{
  "address": "0x76ba3eC5f5adBf1C58c91e86502232317EeA72dE",
  "symbol": "dLP RDNT",
  "decimals": 18,
  "methodABI": {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "lockedBalances",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "total",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "output": "total"
}
```

2023-03-25 14:29 UTC, JDoy99 commented on src/strategies/rdnt-capital-dlp/index.ts
Ahh awesome! Thanks so much for that. I do actually have another strategy which I need to make, so I wonder if its easier for me to dm you to ask for advice on it, would that be ok @ChaituVR?

2023-03-28 20:25 UTC, ChaituVR requested changes

2023-03-28 20:25 UTC, ChaituVR commented on src/strategies/rdnt-capital-locked-dlp/index.ts
> +];
```suggestion
const abi = [ 'function lockedUsdValue(address user) view returns (uint256)' ];
```

2023-03-28 20:25 UTC, ChaituVR commented on src/strategies/rdnt-capital-locked-dlp/index.ts
> +  }
Hi @JDoy99 Move this function to the outside strategy function

2023-03-28 20:25 UTC, ChaituVR commented on src/strategies/rdnt-capital-locked-dlp/index.ts
> +    return data[0].current_price;
The price should be depended on `snapshot or its timestamp, else voting power will not be same as expected everytime, and can cause lot of problems, refer to this implementation https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/digitalax-genesis-contribution/index.ts#L137-L139
It should calculate voting power based on timestamp

2023-03-31 17:47 UTC, ChaituVR commented on src/strategies/rdnt-capital-voting/README.md
> +}
```suggestion
{
        "rdnt": "0x3082cc23568ea640225c2467653db90e9250aaa0",
        "lpToken": "0x32DF62DC3AED2CD6224193052CE665DC18165841",
        "lockingContract": "0x76ba3eC5f5adBf1C58c91e86502232317EeA72dE",
        "balancerPoolId": "0x32df62dc3aed2cd6224193052ce665dc181658410002000000000000000003bd",
        "balancerVault": "0xBA12222222228d8Ba445958a75a0704d566BF2C8"
      }
```

2023-04-01 04:07 UTC, ChaituVR approved these changes

2023-04-01 04:08 UTC, merged