[vault-token-lp-balance] Adding farmersonly-fox-in-vaults strategy for FarmersOnlyFi DAO
snapshot-labs/snapshot-strategies pull request #112
Opened 2021-10-17 02:38 UTC by FoxTheFarmer

Changes proposed in this pull request:
- Adding farmersonly-fox-in-vaults strategy for FarmersOnlyFi DAO

2021-10-17 12:31 UTC, ChaituVR requested changes

2021-10-17 12:31 UTC, ChaituVR commented on src/strategies/farmersonly-fox-in-vaults/index.ts
> +  const userVaultFoxBalances: any = vaultFoxPools.map(async (vault) => {
@FoxTheFarmer I see more than 10 multicall in this strategy, but we have a limit for this
```
There should be a maximum of 5 requests, a request can use "fetch" a "subgraphRequest" or "multicall".
```
https://github.com/snapshot-labs/snapshot-strategies#checklist-for-adding-a-new-strategy


Please check if there is an alternate way to get this :)

2021-10-18 05:23 UTC, ChaituVR requested changes
Thanks @FoxTheFarmer  Just remove these logs, everything else looks good to go

2021-10-18 05:23 UTC, ChaituVR commented on src/strategies/single-staking-vault-balanceof/index.ts
> +  console.log('vaultBalances', vaultBalances);
```suggestion
```

2021-10-18 05:23 UTC, ChaituVR commented on src/strategies/vault-token-lp-balance/index.ts
> +  console.log(vaultBalances);
```suggestion
```

2021-10-18 17:57 UTC, ChaituVR commented
@FoxTheFarmer Please resolve conflicts

2021-10-18 19:10 UTC, bonustrack approved these changes

2021-10-19 07:22 UTC, merged