[battlefly-vgfly-and-staked-gfly]Feature/battlefly dao voting upgrade for founders voting
snapshot-labs/snapshot-strategies pull request #1146
Opened 2023-04-28 16:52 UTC by Archethect

Upgrade for the battlefly strategy that allows voting with Battlefly founders tokens.

2023-04-28 19:15 UTC, ChaituVR requested changes

2023-04-28 19:15 UTC, ChaituVR commented on src/strategies/battlefly-vgfly-and-staked-gfly/index.ts
Also update the version plz :)
```
export const version = '0.0.1';
```

2023-04-29 07:07 UTC, Archethect commented on src/strategies/battlefly-vgfly-and-staked-gfly/index.ts
done!

2023-04-29 18:05 UTC, ChaituVR approved these changes

2023-04-29 18:05 UTC, merged