Add dps nft stratey nova
snapshot-labs/snapshot-strategies pull request #1156
Opened 2023-05-10 12:43 UTC by andreibadea20

Fixes # .

Changes proposed in this pull request:
- add new strategy for nova network
- created a pull request for adding nova network if you can take a look
-

2023-05-10 20:20 UTC, ChaituVR requested changes

2023-05-10 20:20 UTC, ChaituVR commented on src/strategies/dps-nft-strategy-nova/README.md
> +# dps-nft-strategy
```suggestion
# dps-nft-strategy-nova
```

2023-05-10 20:20 UTC, ChaituVR commented on src/strategies/dps-nft-strategy-nova/index.ts
> +export const version = '0.3.0';
```suggestion
export const version = '0.1.0';
```

2023-05-12 08:20 UTC, andreibadea20 commented
yeah, the test cases are falling, because nova network is not in your supported networks list. I've added the network and I'm waiting for a reply for my PR

2023-05-15 10:29 UTC, merged