Improve skale delegation weighted strategy
snapshot-labs/snapshot-strategies pull request #1193
Opened 2023-06-15 21:08 UTC by payvint

Hey Snapshot team!!

It is pleasure to contribute to your repo again!

So after my previous contribution, we decided to add more functionality to the strategy, so now not only delegators can vote but validators as well, and the strategy is modifiable
 
Changes proposed in this pull request:
- Calculate validators vote as well
- Using graph requests
- Add params to turn on/off validators vote

Please review it and let me now your thoughts!
Thanks!

2023-06-19 18:37 UTC, ChaituVR requested changes

2023-06-19 18:39 UTC, payvint commented on src/strategies/skale-delegation-weighted/index.ts
> +      },
You can see that there 2 different function (with block and without)

If it is without - it will use latest

2023-06-19 18:41 UTC, payvint commented on src/strategies/skale-delegation-weighted/index.ts
> +      },
If block does not specify in strategy("latest") - it will use latest

2023-06-19 18:46 UTC, ChaituVR commented on src/strategies/skale-delegation-weighted/index.ts
> +      },
Ah that confused me 😅 can do something like https://github.com/snapshot-labs/snapshot-strategies/blob/mastersrc/strategies/balance-of-subgraph/index.ts#L33-L36 will reduce some code :)

2023-06-19 18:52 UTC, payvint commented on src/strategies/skale-delegation-weighted/index.ts
> +      },
Let me check:)

Overall there are 2 conditions:
On line 204 and line 230 - where it checks is block number specified

2023-06-19 20:57 UTC, payvint commented on src/strategies/skale-delegation-weighted/index.ts
> +      },
Hey @ChaituVR please check again!

Simplified code as you suggested:)

2023-06-20 18:25 UTC, ChaituVR commented
HI @payvint somehow your test cases never end? did you try running `yarn test --strategy=<your-strategy-name>` in your local?

2023-06-20 18:36 UTC, payvint commented
> HI @payvint somehow your test cases never end? did you try running `yarn test --strategy=<your-strategy-name>` in your local?

Hey yes I tried, but unfortunately it never ends for me for all tests which I tried(erc20 as well) - so I thought it is on your side

I have tried to see what the process is running - but nothing showed up

So I saw that all the tests passed (with 500 addresses as well) and pushed

2023-06-20 19:18 UTC, payvint commented
Hey @ChaituVR it shows me that snapshot.js is opened on tests for every strategy which I running
![Screenshot 2023-06-20 at 20 15 19](https://github.com/snapshot-labs/snapshot-strategies/assets/15244661/730b3933-a26e-47de-a1b4-c82d643eabe0)

2023-06-20 20:04 UTC, payvint commented
Hey @ChaituVR looks like this line is not allowing to close the handle
https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils/blockfinder.ts#L33

2023-06-20 20:56 UTC, payvint commented
> HI @payvint somehow your test cases never end? did you try running `yarn test --strategy=<your-strategy-name>` in your local?

So just did an analysis
On snapshot.js version 0.4.99 and 0.4.98 it works infinitely - till the timeout of test
Ob version 0.4.97 - finished successfully

2023-06-20 20:58 UTC, payvint commented
Looks like after this PR all the strategies tests are running infinitely 
https://github.com/snapshot-labs/snapshot.js/pull/851

2023-06-20 21:09 UTC, payvint commented
Created an issue
https://github.com/snapshot-labs/snapshot.js/issues/856

2023-06-21 09:46 UTC, ChaituVR commented
Thank you so much for spotting this @payvint 🙏 :) fixed it now

2023-06-21 09:49 UTC, ChaituVR approved these changes

2023-06-21 09:50 UTC, merged

2023-06-21 09:56 UTC, payvint commented
Thank you for merging!
It unblocks us to create a government!