[hats-protocol-hat-id] Fix hats-protocol-hat-id strategy
snapshot-labs/snapshot-strategies pull request #1367
Opened 2023-12-01 19:26 UTC by gershido

Fixes hats-protocol-hat-id strategy.

Changes proposed in this pull request:
- Fix hat ID conversion
- Remove subgraph usage
- Use a multi-call to get the wearers of the hat

2023-12-02 06:53 UTC, ChaituVR requested changes
Hi @gershido PR should be coming from `hotmanics` as they are the author

2023-12-02 06:53 UTC, ChaituVR commented on src/strategies/hats-protocol-hat-id/index.ts
Abi can be
```
[
  'function isWearerOfHat(address _user, uint256 _hatId) view returns (bool isWearer)'
]
```

2023-12-03 21:49 UTC, Hotmanics commented
> Hi @gershido PR should be coming from `hotmanics` as they are the author

Hey @ChaituVR. We decided to let @gershido do the PR as he was the one that ultimately found and fixed the bug, so just wan't to give him credit where its due. Is it possible for him to follow through on this? Otherwise I'm sure I can just make the changes and a PR from my account.

2023-12-04 07:03 UTC, ChaituVR approved these changes

2023-12-04 07:05 UTC, merged