add blp strategy
snapshot-labs/snapshot-strategies pull request #1394
Opened 2024-01-23 04:12 UTC by SpaceFinance

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2024-01-23 04:49 UTC, ChaituVR requested changes
Hi @SpaceFinance Could you please add a readme to this strategy? will help users know more about it

2024-01-23 05:31 UTC, SpaceFinance commented
[README.md](https://github.com/snapshot-labs/snapshot-strategies/files/14018698/README.md)

2024-01-23 07:48 UTC, SpaceFinance commented
> Hi @SpaceFinance Could you please add a readme to this strategy? will help users know more about it

Added, please check

2024-01-23 10:59 UTC, ChaituVR requested changes

2024-01-23 10:59 UTC, ChaituVR commented on src/strategies/spacefi-blp/index.ts
> +export const author = 'icepoint';
```suggestion
export const author = 'SpaceFinance';
```

2024-01-23 10:59 UTC, ChaituVR commented on src/strategies/spacefi-blp/index.ts
> +export const version = '0.1.1';
```suggestion
export const version = '0.1.0';
```

2024-01-24 09:25 UTC, ChaituVR requested changes
should add strategy to /src/strategies/index.ts like all other strategies

2024-01-24 10:24 UTC, SpaceFinance commented
> should add strategy to /src/strategies/index.ts like all other strategies

Added Completed

2024-01-24 11:14 UTC, ChaituVR commented
Tests are failing can take a look? try running `yarn test --strategy=spacefi-blp --more=500` in your local

2024-01-25 07:48 UTC, SpaceFinance commented
> Tests are failing can take a look? try running `yarn test --strategy=spacefi-blp --more=500` in your local

Modified, please check

2024-01-25 09:01 UTC, ChaituVR approved these changes

2024-01-25 09:03 UTC, merged