Voting Strategy updated for New V3 Farm
snapshot-labs/snapshot-strategies pull request #1402
Opened 2024-02-01 10:26 UTC by defininja

Fixes # .

Changes proposed in this pull request:
- added logic to increase voting weight for staking in v3 pools
- calculated user staked Aqua balance in Aqua-Btcb pool
- calculated user staked Aqua balance in Aqua Pool
- Added above two Aqua Balance to User's Vote weight
- new formula for voting
```
user's voting score  = user's wallet aqua balance + aqua balance in v2 aqua-bnb pool + 5 times the aqua balance in v2 infinity vault  + aqua balance in lending + 5 times the aqua balance in v3 aqua pool + aqua balance in v3 aqua-btcb pool
```

2024-02-01 11:02 UTC, ChaituVR requested changes

2024-02-01 11:02 UTC, ChaituVR commented on src/strategies/planet-finance-v2/index.ts
> +    usersEarningSharesInAquaBtcbPool
This will cross our limit of 5 network calls, refer to https://github.com/snapshot-labs/snapshot-strategies?tab=readme-ov-file#code

2024-02-01 14:53 UTC, defininja commented
@ChaituVR - I have changed my code to use 5 network calls. Please review and merge my code. Thanks

2024-02-04 18:00 UTC, ChaituVR requested changes
Hi @defininja It still call 6 network calls, there is one at line `151` apart from 5 calls in `promise.all`

2024-02-05 18:48 UTC, ChaituVR commented on src/strategies/planet-finance-v2/index.ts
>  export const version = '0.0.2';
```suggestion
export const version = '0.1.0';
```

2024-02-05 18:51 UTC, ChaituVR reviewed
I see a active proposal for this strategy 
https://snapshot.org/#/planetfinance.eth/proposal/0x465d9939f333c6f5f778b29adfa25d19a8d6f9dbf1b616f01970a0cd85a8392a

Better to wait for it to be closed before merging this to avoid confusions with voting power.

2024-02-16 08:42 UTC, defininja commented
@ChaituVR - Above proposal is closed now. Please approve the merge request.

2024-02-21 06:15 UTC, ChaituVR approved these changes

2024-02-21 06:15 UTC, merged