[single-staking-longtermstaking-balanceof] strategy for long term vault balance
snapshot-labs/snapshot-strategies pull request #1430
Opened 2024-03-13 20:22 UTC by macaronchef

Added new strategy for Long Term Staking Vault

2024-03-14 05:15 UTC, ChaituVR approved these changes

2024-03-14 05:33 UTC, ChaituVR requested changes
Hi @macaronchef you have add your strategy single-staking-longtermstaking-balanceof to src/strategies/index.ts

2024-03-14 10:35 UTC, macaronchef commented
> Hi @macaronchef you have add your strategy single-staking-longtermstaking-balanceof to src/strategies/index.ts

Hi @ChaituVR I added strategy to index.ts

2024-03-14 11:07 UTC, ChaituVR commented on src/strategies/index.ts
> +import * as singleStakingLongTermStakingBalanceOf from './single-staking-longterm-staking-balanceof';
```suggestion
import * as singleStakingLongTermStakingBalanceOf from './ssingle-staking-longtermstaking-balanceof';
```

2024-03-14 11:07 UTC, ChaituVR requested changes

2024-03-14 11:07 UTC, ChaituVR commented on src/strategies/index.ts
> +  'single-staking-longterm-staking-balanceof': singleStakingLongTermStakingBalanceOf,
```suggestion
  'single-staking-longtermstaking-balanceof': singleStakingLongTermStakingBalanceOf,
```

2024-03-14 16:05 UTC, ChaituVR commented on src/strategies/index.ts
> +import * as singleStakingLongTermStakingBalanceOf from './ssingle-staking-longtermstaking-balanceof';
```suggestion
import * as singleStakingLongTermStakingBalanceOf from './single-staking-longtermstaking-balanceof';
```

2024-03-14 16:10 UTC, ChaituVR requested changes
Looks like test cases are failing , can take a look @macaronchef ?

2024-03-18 20:09 UTC, macaronchef commented
Tests and other issues fixed. Please review again @ChaituVR Thanks

2024-03-19 02:20 UTC, ChaituVR approved these changes

2024-03-19 02:20 UTC, merged