update subgraph URL
snapshot-labs/snapshot-strategies pull request #1433
Opened 2024-03-14 09:54 UTC by tangobeo

Fixes # .

Changes proposed in this pull request:
- update subgraph URL

2024-03-14 11:08 UTC, ChaituVR commented
@edwardEvans094 Could you confirm this change ?

2024-03-14 11:10 UTC, ChaituVR commented
@toniqhz  Could you confirm this change ?

2024-03-14 11:10 UTC, ChaituVR commented on src/strategies/faraland-staking/index.ts
>  export const author = 'edwardEvans094';
```suggestion
export const author = 'toniqhz';
```

2024-03-15 02:54 UTC, toniqhz commented on src/strategies/faraland-staking/index.ts
>  export const author = 'edwardEvans094';
its ok, pls merge

2024-03-15 05:24 UTC, ChaituVR requested changes
@tangobeo test cases are failing, can take a look? 

<img width="1101" alt="image" src="https://github.com/snapshot-labs/snapshot-strategies/assets/15967809/6820b7d9-c40d-4760-b2e7-46820638f59e">

You need to pass a address that has voting power with latest block

2024-03-15 07:34 UTC, tangobeo commented
> @tangobeo test cases are failing, can take a look?
> 
> <img alt="image" width="1101" src="https://private-user-images.githubusercontent.com/15967809/313076877-6820b7d9-c40d-4760-b2e7-46820638f59e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODgzMjAsIm5iZiI6MTcxMDQ4ODAyMCwicGF0aCI6Ii8xNTk2NzgwOS8zMTMwNzY4NzctNjgyMGI3ZDktYzQwZC00NzYwLWIyZTctNDY4MjA2MzhmNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA3MzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MTVjYTlhODk3ZTBkMmRiZDdkMWEyYmRmYmIzMzUyNjA3YjY3MDA2YTFkNzU1NTFkYTRmZjkxZDgwNGI4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrL1pWlCEI5nbsmZOONZ3J7eXfp3GdzGkto9SJGxye8">
> You need to pass a address that has voting power with latest block

I just update it, please check again. Thank you!

2024-03-15 08:17 UTC, ChaituVR approved these changes

2024-03-15 08:17 UTC, merged