Add xdai-stake-lp strategy
snapshot-labs/snapshot-strategies pull request #15
Opened 2021-08-09 14:20 UTC by maxaleks

This strategy returns STAKE token balances of Uniswap and Sushiswap liquidity providers

2021-08-09 14:33 UTC, ChaituVR requested changes

2021-08-09 14:33 UTC, ChaituVR commented on src/strategies/xdai-stake-lp/index.ts
> +];
```suggestion
const abi = ['function balanceOf(address owner) view returns (uint256)'];
```

2021-08-09 14:33 UTC, ChaituVR commented on src/strategies/xdai-stake-lp/index.ts
> +};
Would be great to use these as default but can also overwrite addresses and URLs if passed from params (examples.json)

2021-08-09 14:33 UTC, ChaituVR commented on src/strategies/xdai-stake-lp/index.ts
> +import examplesFile from './examples.json';
Examples JSON imported automatically now (with new changes) :) you can remove this
```suggestion
```

2021-08-09 14:33 UTC, ChaituVR commented on src/strategies/xdai-stake-lp/index.ts
> +export const examples = examplesFile;
Examples JSON imported automatically now (with new changes) :) you can remove this
```suggestion
```

2021-08-09 17:42 UTC, bonustrack commented
@maxaleks Hey, actually we already have a strategies that does this, one is called "sushiswap" and "uniswap" (for V2), does your strategy add something more? If not it's preferable to use the generic strategies for it.

2021-08-09 18:16 UTC, maxaleks commented
@bonustrack Hey, the Sushiswap strategy does not take into account that most liquidity providers send their LP tokens to the Master Chef contract. But you're right, I can update the existing Sushiswap strategy instead of creating a new one

2021-08-10 05:43 UTC, ChaituVR commented
@maxaleks Cool then, closing the PR for now, we will wait for PR on sushiswap strategy, feel free to reopen this PR if required :) Thanks

2021-08-10 05:43 UTC, closed without merging

2021-08-10 08:44 UTC, bonustrack commented
@maxaleks That would be the best yea so we don't duplicate code. If you going to change the sushiswap strategy to include LP tokens in the master chef contract i recommend to make this optional, so it doesnt change results on proposals using currently that strategy.