Coinswap
snapshot-labs/snapshot-strategies pull request #159
Opened 2021-11-12 11:55 UTC by PawelGozdz

Fixes # .

Changes proposed in this pull request:
- coinswap strategy added

2021-11-12 17:26 UTC, ChaituVR requested changes
Hello @PawelGozdz Please resolve conflicts

2021-11-12 17:26 UTC, ChaituVR commented on src/strategies/coinswap/index.ts
> +export const author = 'coinswap';
```suggestion
export const author = 'CoinSwap-Space';
```

2021-11-14 06:49 UTC, bonustrack approved these changes

2021-11-14 07:02 UTC, ChaituVR approved these changes

2021-11-14 07:02 UTC, merged

2021-11-14 10:46 UTC, ChaituVR commented on src/strategies/coinswap/index.ts
> +  const blockTag = 'latest';
Hi, @PawelGozdz I just noticed that you are not using the `snapshot` block number to get the result here, and the voting power generated by this strategy will keep changing in the future, this is not expected behaviour for a strategy in snapshot

Please add a fix to this or this strategy will be disabled soon,

Thanks