Strategy for allowing those with vested deversifi tokens on-chain to vote
snapshot-labs/snapshot-strategies pull request #17
Opened 2021-08-09 17:56 UTC by plutoegg

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-08-10 05:31 UTC, ChaituVR requested changes

2021-08-10 05:31 UTC, ChaituVR commented on src/strategies/vested-deversifi/index.ts
> +];
```suggestion
const vestedABI = [ 'function delegateForVoting() view returns (address)' ];
```

2021-08-10 05:31 UTC, ChaituVR commented on src/strategies/vested-deversifi/index.ts
> +];
```suggestion
const xDVFABI = [ 'function balanceOf(address account) view returns (uint256)' ];
```

2021-08-10 11:59 UTC, plutoegg commented
Hi @ChaituVR formatting of the ABIs has been resolved :)

2021-08-10 16:51 UTC, bonustrack approved these changes

2021-08-11 05:36 UTC, ChaituVR approved these changes

2021-08-11 05:36 UTC, merged

2021-08-11 05:45 UTC, ChaituVR commented
Strategy is live here: https://snapshot.org/#/strategy/vested-deversifi