Strategy tomyumswap added
snapshot-labs/snapshot-strategies pull request #176
Opened 2021-11-21 12:22 UTC by tomyumswap

Fixes # .

Changes proposed in this pull request:
- New strategy with the name tomyumswap has been added
- Based on the token TOMYUM
- Minimum voting power needed: 0.1
- Voting power and subgraph endpoints have been changed

All test cases are passing

2021-11-22 04:26 UTC, ChaituVR requested changes

2021-11-22 04:26 UTC, ChaituVR commented on src/strategies/tomyumswap/index.ts
> +    const votingPowerResults = await Promise.all(promises);
Hi @tomyumswap sending one request per address won't scale for a large number of votes, please find an alternate way to get all data for all addresses in a single request
https://github.com/snapshot-labs/snapshot-strategies#checklist-for-adding-a-new-strategy

2021-11-22 04:29 UTC, tomyumswap commented
Hi Chaitanya

The same code is working for Pancake (strategy name: cake) and AKS
(strategy name: aks) strategy.

On Mon, 22 Nov, 2021, 9:56 am Chaitanya, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/strategies/tomyumswap/index.ts
> <https://github.com/snapshot-labs/snapshot-strategies/pull/176#discussion_r753936903>
> :
>
> > +    const promises = addresses.map((address) => {
> +      return fetchVotingPower(address, blockTag, poolAddresses);
> +    }) as ReturnType<typeof fetchVotingPower>[];
> +    const votingPowerResults = await Promise.all(promises);
>
> Hi @tomyumswap <https://github.com/tomyumswap> sending one request per
> address won't scale for a large number of votes, please find an alternate
> way to get all data for all addresses in a single request
>
> https://github.com/snapshot-labs/snapshot-strategies#checklist-for-adding-a-new-strategy
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/snapshot-labs/snapshot-strategies/pull/176#pullrequestreview-812065857>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV7YAKSV4WB5NZEHDRKPC5LUNHBBBANCNFSM5IPDFVFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 16:54 UTC, ChaituVR commented
Probably `cake` strategy needs to be changed too, on aks strategy, it is not doing for all addresses, 🤔 if we don't change, it won't def. scale for larger votings

2021-11-23 07:28 UTC, tomyumswap commented
Hi Chaitanya

Pls check the latest [commit](https://github.com/snapshot-labs/snapshot-strategies/pull/176/commits/4c3d9147f03b91d385980409af05480a27f1599b). I have changed the API to include an array of addresses for fetching the voting power. This should fix the scalability issue of the addresses.

2021-11-23 11:33 UTC, bonustrack approved these changes

2021-11-23 12:27 UTC, ChaituVR approved these changes

2021-11-23 12:27 UTC, merged