Add StackedToadz strategy [unstackedtoadz-and-stackedtoadz-stakers]
snapshot-labs/snapshot-strategies pull request #217
Opened 2021-12-06 03:07 UTC by Eh-Marine

Changes proposed in this pull request:
- Added strategy to account for only StackedToadz and UnstackedToadz stakers for the StackedToadz project which is required for governance voting.
- Voting power determined by (number of StackedToadz staked + number of UnstackedToadz staked).

2021-12-07 07:53 UTC, ChaituVR requested changes

2021-12-07 07:53 UTC, ChaituVR commented on src/strategies/unstackedtoadz-and-stackedtoadz-stakers/index.ts
> +export const author = 'Eh_Marine';
```suggestion
export const author = 'Eh-Marine';
```

2021-12-07 08:35 UTC, Eh-Marine reviewed
thanks

2021-12-08 11:08 UTC, bonustrack approved these changes

2021-12-08 11:10 UTC, ChaituVR approved these changes

2021-12-08 11:10 UTC, merged