Add custom strategy for minmax finance
snapshot-labs/snapshot-strategies pull request #219
Opened 2021-12-06 23:40 UTC by LeifuChen

This is a custom strategry for minmax finance.
This strategy returns the total amount of user-owned MAX tokens as the voting power, including MAX in wallets, pending rewards and MAX LP held by the [farm contract](https://farm.mcn.ventures/farms) on iotex.

2021-12-07 07:56 UTC, ChaituVR requested changes
Hello @LeifuChen We need to import the strategy into this file https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/index.ts

2021-12-07 08:39 UTC, LeifuChen commented
@ChaituVR Thanks for your remind. I forgot adding it into the commits after local testing. Is it ok now?

2021-12-07 18:21 UTC, ChaituVR requested changes

2021-12-07 18:21 UTC, ChaituVR commented on src/strategies/index.ts
> +  'snet-liquidity-providers': snetLiquidityProviders，
```suggestion
  'snet-liquidity-providers': snetLiquidityProviders,
```

2021-12-08 11:09 UTC, bonustrack approved these changes

2021-12-08 11:13 UTC, ChaituVR approved these changes

2021-12-08 11:13 UTC, merged