Adds Lydia governance vault strategy
snapshot-labs/snapshot-strategies pull request #232
Opened 2021-12-11 07:46 UTC by manes-codes

2021-12-11 17:30 UTC, ChaituVR requested changes

2021-12-11 17:30 UTC, ChaituVR commented on src/strategies/lydia-gov-vault/index.ts
> +];
```suggestion
const abi = [
  'function sharesOf(address account) view returns (uint256)',
  'function getPricePerFullShare() view returns (uint256)'
];
```

2021-12-11 21:06 UTC, bonustrack approved these changes

2021-12-12 14:37 UTC, ChaituVR approved these changes

2021-12-12 14:37 UTC, merged