Add an ERC20-balance-of-nft-gated Strategy.
snapshot-labs/snapshot-strategies pull request #238
Opened 2021-12-12 23:51 UTC by blakewest

Changes proposed in this pull request:
- Add a new strategy called `erc20-balance-of-nft-gated`
- This strategy will let you use the balance of an ERC20 token, except you must also possess any arbitrary NFT (both ERC721 and ERC1155 are supported)
- This is useful for using an identity NFT (such as [UID](https://etherscan.io/address/0xba0439088dc1e75F58e0A7C107627942C15cbb41)) in order to enable things like quadratic voting with on-chain sybil protection. But any NFT (eg. PUNKS) could be used.

2021-12-14 04:01 UTC, blakewest commented
@ChaituVR I see the `changes-requested` tag, but I don't see any comments or changes that have been requested. Can you clarify what you'd like to see?

2021-12-14 10:35 UTC, ChaituVR requested changes

2021-12-14 10:36 UTC, ChaituVR commented on src/strategies/erc20-balance-of-nft-gated/index.ts
> +  ];
@blakewest sorry :) forgot to publish the review (small change)

2021-12-16 01:46 UTC, blakewest commented
@ChaituVR updated!

2021-12-19 08:10 UTC, bonustrack reviewed
It would be great if you make this strategy more general purpose, currently it seem to work only for ERC20 as voting power with NFT validation, but ideally it should be made in a way that you could use any strategy as voting power and any strategy as validation. For example we could use ERC721 strategy as voting power and BrightID strategy as validation. I would recommend use a structure like this:
```
{
   votingPowerStrategy: {
      name: 'erc20-balance-of',
      params: {
         address: '0x123243...',
         decimals: 18
      }
   }
   validationStrategy: {
      name: 'brightid',
      params: {}
   }
}
```
 This would give much more freedom

2021-12-20 03:45 UTC, blakewest commented
@bonustrack ah, good call! I dig that. I'll take a crack at it.

2021-12-21 23:42 UTC, blakewest commented
@bonustrack and @ChaituVR updated!

2021-12-24 16:55 UTC, bonustrack reviewed
@blakewest Looks good, could you just rename the strategy to just "membership"?

2021-12-27 23:42 UTC, blakewest commented
@bonustrack I updated the name. Though I worry the name is not very descriptive, and people might confuse it with something where your voting power is like 1 or 0 based on a membership. As I write this out, do you think `members-only-voting` would be better? I'm also fine to just get this merged in. We'd like to use this very soon, so I want to make sure it's in, and we can do some initial tests.

2021-12-29 02:26 UTC, blakewest commented
@ChaituVR I see a couple tests are failing. But looks like it's from a server error on the specs. Can you re-run? Or are we good to merge as is? Let me know if I can help. Thanks! - Blake

2021-12-29 15:56 UTC, bonustrack commented
@blakewest Hmm I don't see so much differences from membership-based-voting or members-only-voting to membership name. Each of them could be confused with 0-1 type of strategy. Ideally I'd like to keep the name as generic as possible so it's easy to remember, I believe this can be a very popular strategy.

2021-12-29 21:29 UTC, blakewest commented
Alright. Sounds good, let's get it merged!

2021-12-30 05:50 UTC, merged