[botto-dao] Adds Botto DAO governance strategy
snapshot-labs/snapshot-strategies pull request #246
Opened 2021-12-15 19:15 UTC by alfonsocarbono

Adds Botto DAO governance strategy

2021-12-16 17:08 UTC, ChaituVR requested changes

2021-12-16 17:08 UTC, ChaituVR commented on src/strategies/botto-dao/index.ts
> +export const author = 'carbonocom';
```suggestion
export const author = 'alfonsocarbono';
```

2021-12-20 11:44 UTC, bonustrack approved these changes

2021-12-20 11:45 UTC, ChaituVR approved these changes

2021-12-20 11:45 UTC, merged