add cronaswap strategies
snapshot-labs/snapshot-strategies pull request #247
Opened 2021-12-17 09:21 UTC by CronaChef

Fixes # .

Changes proposed in this pull request:
- add cronaswap strategies

This is the most common strategy, it returns the balances of the voters for a balances CRONA token
in CronaSwap project(pools, farms, Liquidity, token).

2021-12-17 09:25 UTC, CronaChef commented
te

2021-12-17 09:45 UTC, CronaChef commented
reopened

2021-12-17 12:34 UTC, ChaituVR requested changes
Plz revert package-lock.json

2021-12-17 12:34 UTC, ChaituVR commented on src/strategies/cronaswap/index.ts
> +export const author = 'cronaswap-dex';
```suggestion
export const author = 'CronaChef';
```

2021-12-18 03:46 UTC, CronaChef commented
> Plz revert package-lock.json

OK revert it. pls check. thanks

2021-12-18 17:05 UTC, ChaituVR requested changes
Hi @CronaChef I see changes in package-lock.json, please remove changes from it

![image](https://user-images.githubusercontent.com/15967809/146649561-71c42023-8237-40c1-81be-a290a3965521.png)

2021-12-19 13:35 UTC, closed without merging