Added Honeyswap strategy
snapshot-labs/snapshot-strategies pull request #25
Opened 2021-08-11 22:37 UTC by kittyslasher

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-08-12 16:06 UTC, ChaituVR requested changes
Hey also add this strategy to `src/strategies/index.ts` thanks

2021-08-12 16:06 UTC, ChaituVR commented on src/strategies/honeyswap/index.ts
> +import { getAddress } from '@ethersproject/address;
Hi @kittyslasher, missed a quote here :) 
```
src/strategies/honeyswap/index.ts(1,52): error TS1002: Unterminated string literal.
```
```suggestion
import { getAddress } from '@ethersproject/address';
```

2021-08-12 16:06 UTC, ChaituVR commented on src/strategies/honeyswap/index.ts
> +export const version = '0.1.1';
```suggestion
export const version = '0.1.0';
```

2021-08-16 16:27 UTC, kittyslasher commented
Thanks for the advice i went ahead and made some edits let me know if its good now! I run npm test and it passes but it did it last time as well.

2021-08-17 07:09 UTC, bonustrack commented on src/strategies/index.ts
> +  'honeyswap': honeyswap,
```suggestion
  honeyswap,
```

2021-08-17 07:09 UTC, bonustrack approved these changes

2021-08-17 07:12 UTC, ChaituVR approved these changes

2021-08-17 07:12 UTC, merged

2021-08-17 07:54 UTC, ChaituVR commented
Strategy is live: https://snapshot.org/#/strategy/honeyswap