[cronaswap] Add strategy for CronaSwap
snapshot-labs/snapshot-strategies pull request #251
Opened 2021-12-19 13:41 UTC by CronaChef

[cronaswap] Add strategy for CronaSwap

2021-12-20 07:30 UTC, ChaituVR requested changes
Hi @CronaChef Looks good but the strategy should be imported into this file https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/index.ts

2021-12-20 09:30 UTC, CronaChef commented
> Hi @CronaChef Looks good but the strategy should be imported into this file https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/index.ts

OK, thanks, added. pls check.

2021-12-21 11:32 UTC, bonustrack approved these changes

2021-12-21 18:36 UTC, ChaituVR approved these changes

2021-12-21 18:36 UTC, merged