Add sunder strategy
snapshot-labs/snapshot-strategies pull request #27
Opened 2021-08-14 11:07 UTC by krotos-arch

Fixes # .

Changes proposed in this pull request:

Sunder is the customized strategy for Sunder protocol. Any governance token been sundered with dToken can choose this strategy to get it included with the original token with 1:1 voting power.

2021-08-15 16:51 UTC, ChaituVR requested changes
Hey, Please remove the changes from `yarn.lock`, Everything else looks good to me :)

2021-08-16 09:45 UTC, ChaituVR requested changes

2021-08-16 09:45 UTC, ChaituVR commented on src/strategies/sunder/index.ts
> +  console.log(result);
Hey please remove these unwanted logs, everything else seems good to go
```suggestion
```

2021-08-16 09:45 UTC, ChaituVR commented on test/index.spec.ts
>      expect(
Please remove these new lines
```suggestion
    expect(
```

2021-08-16 10:19 UTC, krotos-arch commented
Can I merge my rp :)

2021-08-16 11:57 UTC, bonustrack approved these changes

2021-08-16 12:25 UTC, ChaituVR approved these changes

2021-08-16 12:25 UTC, merged

2021-08-16 12:36 UTC, ChaituVR commented
Strategy live here: https://snapshot.org/#/strategy/sunder