removed liquidity pools from voting and supply
snapshot-labs/snapshot-strategies pull request #287
Opened 2022-01-06 11:26 UTC by frosti-eth

Changes proposed in this pull request:
- blacklist LP addresses from voting and remove their balances from total supply

2022-01-06 17:51 UTC, ChaituVR requested changes

2022-01-06 17:51 UTC, ChaituVR commented on src/strategies/cyberkongz/index.ts
> +
Hello @frosti-eth we can't update this as it can affect existing space that are using this strategy

2022-01-06 18:24 UTC, frosti-eth commented
Hello,

The only space that uses this strategy is our own, and our contract addresses are hardcoded in there. I think we’re good to merge this, but if you like we could submit a _v2 PR? Do you need a wallet signature somewhere?

frosti


> On Jan 6, 2022, at 19:51, Chaitanya ***@***.***> wrote:
> 
> ﻿
> @ChaituVR requested changes on this pull request.
> 
> In src/strategies/cyberkongz/index.ts:
> 
> > +  response.forEach((value: any, i: number) => {
> +    const address = calls[i][2][0];
> +    if (Math.floor(i / addresses.length) == 2 && blacklistedAddresses.find((add) => add === address)) {
> +      nanaSupply -= value;
> +    }    
> +  });
> +
> Hello @frosti-eth we can't update this as it can affect existing space that are using this strategy
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-01-06 21:07 UTC, frosti-eth commented
Did we want to run the 500 address test again? That part of the code was not changed from the existing version

2022-01-07 07:13 UTC, ChaituVR commented
@frosti-eth I think it is better to create a -v2 strategy than changing the existing one. so we don't effect existing proposals :)

2022-01-07 08:43 UTC, closed without merging