[aavegotchi] newer staking pool power
snapshot-labs/snapshot-strategies pull request #294
Opened 2022-01-09 17:31 UTC by candoizo

Changes proposed in this pull request:
- add logic to calculate new staking pools

2022-01-10 07:11 UTC, ChaituVR commented
Hi @candoizo Existing proposals could be affected by this change, especially the proposal that is open 
https://snapshot.org/#/aavegotchi.eth/proposal/0x396844d504394f7f335f070d443c33455300ee21d90db6c4b089760a3e0469bf

It is better to create a `-v2` strategy for this

2022-01-11 05:15 UTC, bonustrack commented
There should be a v2 of the strategy if you don't want past proposal to have different results

2022-01-15 10:13 UTC, candoizo commented
In this case after reviewing with team the preferred option is to apply the change on the existing strategy

2022-01-17 05:51 UTC, ChaituVR requested changes

2022-01-17 05:51 UTC, ChaituVR commented on src/strategies/aavegotchi/index.ts
>  const tokenAbi = [
Please replace ABI with this one 
```
[
  'function balanceOf(address account) view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function stakedInCurrentEpoch(address _account) view returns (tuple(address poolAddress, string poolName, string poolU
rl, uint256 rate, uint256 amount)[] _staked)',
  'function staked(address _account) view returns (uint256 ghst_, uint256 poolTokens_, uint256 ghstUsdcPoolToken_)'      
]
```

2022-01-18 14:46 UTC, candoizo commented on src/strategies/aavegotchi/index.ts
>  const tokenAbi = [
fixed!

2022-01-20 09:19 UTC, bonustrack approved these changes

2022-01-20 11:33 UTC, ChaituVR approved these changes

2022-01-20 11:33 UTC, merged