[staked-uniswap-modifiable] strategy to allow modification of method ABI to get balance in uniswap LP staking contract
snapshot-labs/snapshot-strategies pull request #305
Opened 2022-01-17 11:23 UTC by doodley1

Changes proposed in this pull request:
- Fork of staked-uniswap to allow a modifiable function instead of the default balanceOf

2022-01-18 06:08 UTC, ChaituVR requested changes

2022-01-18 06:08 UTC, ChaituVR commented on src/strategies/staked-uniswap-modifiable/index.ts
> +];
```suggestion
const tokenAbi = [
  'function balanceOf(address account) view returns (uint256)',
  'function totalSupply() view returns (uint256)'
]
```

2022-01-20 14:57 UTC, bonustrack approved these changes

2022-01-20 16:35 UTC, ChaituVR approved these changes

2022-01-20 16:35 UTC, merged