[strategy] digitalax-deco-to-mona new strategy
snapshot-labs/snapshot-strategies pull request #314
Opened 2022-01-20 20:02 UTC by onigiri-x

This is a new strategy for Digitalax

What it does is queries your balance of our DECO token

Converts to ETH value

Converts to MONA value

For our MONA based snapshot voting

Uses a certain subgraph for quickswap to get the pair conversion prices

Cheers

2022-01-21 08:26 UTC, ChaituVR requested changes

2022-01-21 08:26 UTC, ChaituVR commented on src/strategies/digitalax-deco-to-mona/index.ts
> +  };
Hi @onigiri-x maybe these prices could be changing in the future or during the voting period? Voting power of users could be changing with time? is there any way to query this with time/block? 

Also i think we can replace these with single query `pairs`
```
{
  pairs(where:{id_in:["0x7ecb3be21714114d912469810aedd34e6fc27736","0x3203bf44d434452b4605c7657c51bfeaf2a0847c"] 

  }){
    token1Price
    token0Price
  }
}
```

2022-01-25 08:47 UTC, bonustrack approved these changes

2022-01-25 13:54 UTC, ChaituVR approved these changes

2022-01-25 13:54 UTC, merged