Revising the BrightID Strategy
snapshot-labs/snapshot-strategies pull request #319
Opened 2022-01-22 03:13 UTC by misterplus

For context:
![image](https://user-images.githubusercontent.com/40316318/150622594-ab97653a-02c0-41c7-8706-d2d870d2593e.png)
As approved by @bonustrack 
![image](https://user-images.githubusercontent.com/40316318/150622596-b0e94177-d406-4cb8-b527-2fdb30e44b7e.png)

Changes proposed in this pull request:
- Revise the current "brightid" strategy to use Official Registries created by BrightID for snapshot while preserving backward compatibility
- Change the "brightid" strategy description to better guide DAOs that need a private registry
- Add a new example for the new use case

I'm not very familiar with how snapshot works under the hood, so my implementation might not be best practices, feel free to change the details as long as it matches the following workflow:
![flow (2)](https://user-images.githubusercontent.com/40316318/150622780-b56bea2d-9716-47eb-b188-6d29e078b4d0.png)

2022-01-25 05:53 UTC, misterplus commented
The frontend site is finished, currently under internal testing, you can view the source code here: https://github.com/SongADAO/songaday-idchain-registration

2022-02-10 10:04 UTC, misterplus commented
SongADAO had finished a frontend site for registering with the official BrightID contract: https://idchain.songadao.org/idchain-registration/
Souce code is available here: https://github.com/SongADAO/songaday-idchain-registration
Technically anyone can implement a similar site for their DAO, or just snapshot users in general.

2022-02-11 17:56 UTC, ChaituVR requested changes

2022-02-11 17:56 UTC, ChaituVR commented on src/strategies/brightid/index.ts
> +    options.registry[0] == "v" ? "74" : network,
Any idea why this fail? 
```
    TypeError: Cannot read properties of undefined (reading 'toLowerCase')

      14 |     const blockTag = typeof snapshot === 'number' ? snapshot : 'latest';
      15 |     const registry = options.registry[0] == "v" ? official[options.registry] : options.registry;
    > 16 |     const response = await (0, utils_1.multicall)(options.registry[0] == "v" ? "74" : network, provider, abi, addresses.map((address) => [
         |                            ^
      17 |         registry,
      18 |         'isVerifiedUser',
      19 |         [address]
```

Try running `yarn test --strategy=brightid --more=500` in your local and make sure it pass all tests

2022-02-24 04:34 UTC, misterplus commented
@ChaituVR I've updated the branch with a version that passes `yarn test --strategy=brightid --more=500`, please take a look.

2022-02-24 08:53 UTC, bonustrack approved these changes
Looks good!

2022-02-24 09:03 UTC, ChaituVR approved these changes

2022-02-24 09:03 UTC, merged