add crucible erc20 balanceOf strategy
snapshot-labs/snapshot-strategies pull request #33
Opened 2021-08-20 13:50 UTC by thegostep

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-08-21 04:29 UTC, ChaituVR requested changes

2021-08-22 07:52 UTC, bonustrack approved these changes

2021-08-22 13:00 UTC, ChaituVR approved these changes

2021-08-22 13:00 UTC, merged

2021-08-22 15:14 UTC, ChaituVR commented
Strategy is live:
https://snapshot.org/#/strategy/crucible-erc20-balance-of

2021-08-24 08:19 UTC, thegostep commented
@ChaituVR Thanks for merging ! Running into an issue when attempting to activate the strategy: https://github.com/snapshot-labs/snapshot-strategies/issues/37#issue-977836614