Adds Banksy Farm DAO strategy
snapshot-labs/snapshot-strategies pull request #335
Opened 2022-01-27 03:00 UTC by BanksyFarm

Changes proposed in this pull request:
- Adds support for reading a value in NFT and adding it. (Same as Sandman Finance)

2022-01-27 06:54 UTC, ChaituVR requested changes
Hi @jordanmessina Looks like this is same as https://github.com/snapshot-labs/snapshot-strategies/pull/324/files why not reuse it?

2022-01-27 06:54 UTC, ChaituVR commented on src/strategies/banksy-dao/index.ts
> +export const author = 'myst4';
```suggestion
export const author = 'BanksyFarm';
```

2022-01-28 19:49 UTC, sandmanfinance commented
Although very similar, the strategies are for two different NFT contracts.
If you check, the ABIs are different.
So they must be different strategies.

Thank you very much.

2022-01-29 06:04 UTC, ChaituVR requested changes

2022-01-29 06:04 UTC, ChaituVR commented on src/strategies/banksy-dao/index.ts
> +    console.log(values[1]);
```suggestion
```

2022-01-29 06:05 UTC, ChaituVR commented
Yea , looks very similar except `getArtWorkOverView`

2022-01-29 06:12 UTC, ChaituVR approved these changes

2022-01-29 06:12 UTC, merged