Razor Network Voting Strategy
snapshot-labs/snapshot-strategies pull request #352
Opened 2022-02-01 11:37 UTC by adi44

A custom strategy for calculating the voting power of stakers and delegators of Razor Network. With this strategy, we will be calculating the total number of equivalent razors that they own for sRAZORs amount. The amount of razor is calculated using the specific formal which is (total stake of staker * Amount of sRAZORs) / total supply.

2022-02-01 11:46 UTC, adi44 commented
@ChaituVR Could you please review our strategy and suggest if any changes needed

2022-02-02 12:39 UTC, ChaituVR commented on src/strategies/razor-network-voting/index.ts
> +  console.log(result);
```suggestion
```

2022-02-02 12:41 UTC, ChaituVR requested changes

2022-02-02 12:41 UTC, ChaituVR commented on src/strategies/razor-network-voting/index.ts
> +          score[Staker.staker] = wei_to_ether(Number(razor_amount));
The addresses from the subgraph are lowecased,  we need to return checksum addresses, you can use getAdress for that, example
https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/synthetix-quadratic/index.ts#L124

2022-02-03 10:02 UTC, adi44 commented
@ChaituVR I have made changes as per comments. 
cc : @SkandaBhat

2022-02-04 11:23 UTC, ChaituVR approved these changes

2022-02-04 11:23 UTC, merged