[snowswap] add snowswap balanceOf strategy
snapshot-labs/snapshot-strategies pull request #38
Opened 2021-08-24 13:12 UTC by jairsnowswap

Create strategy for voting with Snowswap balances.

![image](https://user-images.githubusercontent.com/84783860/130622428-d2a9481b-603f-457a-832f-ad4b11c7acb6.png)

Relevant links:

https://snapshot.org/#/snowswap.eth

2021-08-24 15:38 UTC, ChaituVR requested changes

2021-08-24 15:38 UTC, ChaituVR commented on src/strategies/snowswap/index.ts
> +export const version = '0.1';
```suggestion
export const author = 'jairsnowswap';
export const version = '0.1.0';
```

2021-08-25 09:26 UTC, bonustrack approved these changes

2021-08-25 10:32 UTC, ChaituVR approved these changes

2021-08-25 10:32 UTC, merged

2021-08-25 10:38 UTC, ChaituVR commented
Strategy is live: https://snapshot.org/#/strategy/snowswap