Feat/safety module strategy
snapshot-labs/snapshot-strategies pull request #413
Opened 2022-02-23 10:55 UTC by mwamedacen

Changes proposed in this pull request:
- new strategy to support bpt powered aave-live safety module (sktAbpt, stkPSPBpt, etc...)

2022-02-23 13:26 UTC, ChaituVR requested changes

2022-02-23 13:26 UTC, ChaituVR commented on src/strategies/safety-module-bpt-power/index.ts
> +export const author = 'paraswap';
```suggestion
export const author = 'mwamedacen';
```

2022-02-24 07:25 UTC, mwamedacen commented on src/strategies/safety-module-bpt-power/index.ts
> +export const author = 'paraswap';
Done, is that ok for you ?

2022-02-25 11:07 UTC, ChaituVR approved these changes

2022-02-25 11:07 UTC, merged