Add FRWC token weighted strategy
snapshot-labs/snapshot-strategies pull request #429
Opened 2022-02-28 16:13 UTC by Meph1587

Add FRWC token weighted strategy.

Changes proposed in this pull request:
- Add a strategy to assign votes to holders of Forgotten Runes Wizard Cult tokens
- No strategy is present to allow multiple ERC721 to be counted with different weights
- Strategy Passes all tests, including if run with >500 addresses

2022-03-02 15:13 UTC, ChaituVR requested changes
Hi I see this strategy is equal to `erc721-multi-registry` except weigts, so is it possible to rename it as `erc721-multi-registry-weighted` ? so others can reuse it if they want to

2022-03-02 18:17 UTC, Meph1587 commented
Updated that, can you review again? Thanks!

2022-03-02 18:38 UTC, cryppadotta commented
Looks good to me 👍

2022-03-03 07:42 UTC, ChaituVR commented on src/strategies/erc721-multi-registry-weighted/index.ts
> +export const author = 'dievardump';
```suggestion
export const author = 'Meph1587';
```

2022-03-03 07:45 UTC, ChaituVR commented on src/strategies/erc721-multi-registry-weighted/index.ts
> +      multipliers.push(options.weights[idx])
```suggestion
      multipliers.push(options.weights[idx] || 1)
```

2022-03-03 07:46 UTC, ChaituVR commented on src/strategies/erc721-multi-registry-weighted/index.ts
> +      multipliers.push(options.weights[idx] || 1)
```suggestion
      multipliers.push(options.weights?[idx] || 1)
```

2022-03-03 07:48 UTC, ChaituVR commented on src/strategies/erc721-multi-registry-weighted/index.ts
> +      multipliers.push(options.weights?[idx] || 1)
```suggestion
      multipliers.push(options.weights[idx] || 1)
```

2022-03-03 07:58 UTC, ChaituVR approved these changes

2022-03-03 07:58 UTC, merged