ve-ribbon
snapshot-labs/snapshot-strategies pull request #433
Opened 2022-03-04 07:19 UTC by chuddster

Fixes # .

Changes proposed in this pull request:
- new strategy for total balance = erc20balance + locked balance in ribbon voting escrow 
- 
-

2022-03-04 07:40 UTC, ChaituVR requested changes

2022-03-04 07:40 UTC, ChaituVR commented on src/strategies/ve-ribbon/index.ts
> +  const result: Record<string, BigNumberish> = await multi.execute();
The first result is being overwritten by the second result, I think for first you can use `erc20-balance-of` strategy

2022-03-04 08:21 UTC, chuddster commented on src/strategies/ve-ribbon/index.ts
> +      parseFloat(formatUnits(BigNumber.from(balance).add(BigNumber.from(resultLocked[address].amount)), options.decimals))
Adds erc20balance (unlocked RBN) + voting escrow balance (locked RBN)

2022-03-05 13:52 UTC, ChaituVR approved these changes

2022-03-07 05:50 UTC, ChaituVR commented on src/strategies/ve-ribbon/index.ts
> +export const version = '0.1.1';
```suggestion
export const version = '0.1.0';
```

2022-03-07 05:51 UTC, merged