[oolongswap] create strategy
snapshot-labs/snapshot-strategies pull request #465
Opened 2022-03-15 20:49 UTC by Quantumlyy

Changes proposed in this pull request:
- Copies Uniswap strategy and adjust values for Oolongswap on Boba

This could in practice be added to the existing Uniswap strategy but that could cause issues if Uniswap ever expands to Boba.

2022-03-16 06:17 UTC, ChaituVR requested changes
Hi make sure to add this strategy to src\strategies\index.ts and run 
```
npm run test --strategy=<STRATEGY NAME> // replace <STRATEGY NAME>
```
in your local 
https://docs.snapshot.org/strategies/create

2022-03-16 06:20 UTC, ChaituVR requested changes

2022-03-16 06:20 UTC, ChaituVR commented on src/strategies/oolongswap/index.ts
> +export const author = 'vfatouros';
```suggestion
export const author = 'Quantumlyy';
```

2022-03-16 12:21 UTC, Quantumlyy commented
```
➜  snapshot-strategies git:(feat/oolongswap) npm run test --strategy=oolongswap     

> @snapshot-labs/strategies@0.1.0 pretest
> npm run build


> @snapshot-labs/strategies@0.1.0 build
> tsc -p .


> @snapshot-labs/strategies@0.1.0 postbuild
> copyfiles -u 1 src/**/*.md dist/ && copyfiles -u 1 src/**/*.json dist/


> @snapshot-labs/strategies@0.1.0 test
> jest test/index.spec.ts --runInBand --testTimeout=120000

  console.log
    [ { '0x4f6798D42feB2A9169F4fBe0f986D005E1b76180': 904.7175327467143 } ]

      at Object.<anonymous> (test/index.spec.ts:48:13)

  console.log
    Resolved in 1.10 sec.

      at Object.<anonymous> (test/index.spec.ts:49:13)

  console.log
    Scores with latest snapshot [ { '0x4f6798D42feB2A9169F4fBe0f986D005E1b76180': 904.7175327467143 } ]

      at Object.<anonymous> (test/index.spec.ts:111:13)

  console.log
    Resolved in 1.25 sec.

      at Object.<anonymous> (test/index.spec.ts:112:13)

 PASS  test/index.spec.ts (5.924 s)
  
Test strategy "oolongswap"
    ✓ Strategy should run without any errors (1114 ms)
    ✓ Should return an array of object with addresses (1 ms)
    ✓ Should take less than 10 sec. to resolve
    ✓ File examples.json should include at least 1 address with a positive score
    ✓ File examples.json must use a snapshot block number in the past (701 ms)
    ✓ File examples.json must have symbol in its strategy params
    ✓ Returned addresses should be either same case as input addresses or checksum addresses (1 ms)
  
Test strategy "oolongswap" with latest snapshot
    ✓ Strategy should run without any errors (1755 ms)
    ✓ Should return an array of object with addresses (2 ms)
  
Test strategy "oolongswap" (with 500 addresses)
    ○ skipped Should work with 500 addresses
    ○ skipped Should take less than 20 sec. to resolve with 500 addresses
  
Others:
    ✓ Author in strategy should be a valid github username (362 ms)
    ✓ Version in strategy should be a valid string
    ○ skipped Check schema (if available) is valid with example.json
    ○ skipped Strategy should work even when strategy symbol is null

Test Suites: 1 passed, 1 total
Tests:       4 skipped, 11 passed, 15 total
Snapshots:   0 total
Time:        6.256 s
Ran all test suites matching /test\/index.spec.ts/i.
```

2022-03-17 04:53 UTC, ChaituVR approved these changes

2022-03-17 04:53 UTC, merged