Update strategy to add miniumum multiplier 1
snapshot-labs/snapshot-strategies pull request #484
Opened 2022-03-22 05:27 UTC by maikir

Changes proposed in this pull request:
- Update strategy to add miniumum multiplier 1 for meebitsScore (instead of just # meebits, up to 20 but minimum prev. 0).

2022-03-22 18:40 UTC, ChaituVR commented
@lightninglu10 Can you confirm these changes?

2022-03-22 19:00 UTC, lightninglu10 approved these changes

2022-03-22 19:01 UTC, lightninglu10 requested changes
@ChaituVR these changes are correct

2022-03-23 05:52 UTC, ChaituVR approved these changes

2022-03-23 05:52 UTC, merged