[cake] fix cake
snapshot-labs/snapshot-strategies pull request #489
Opened 2022-03-23 12:17 UTC by chef-jojo

Changes proposed in this pull request:
-  while trying to move vp to subgraph, here to fix at least make cake works

2022-03-23 16:51 UTC, ChaituVR commented
Hi @chef-jojo these changes can affect the voting power? or will it return the same as before?

2022-03-24 03:27 UTC, chef-jojo commented
> Hi @chef-jojo these changes can affect the voting power? or will it return the same as before?

Hi @ChaituVR 
these changes currently missing pool voting power https://github.com/snapshot-labs/snapshot-strategies/pull/480
We will update it once subgraph sync is completed

2022-03-24 06:55 UTC, ChaituVR requested changes

2022-03-24 06:55 UTC, ChaituVR commented on src/strategies/cake/index.ts
> +];
```suggestion
const abi = [
  'function getVotingPowerWithoutPool(address _user) view returns (uint256)'
];
```

2022-03-24 06:58 UTC, ChaituVR approved these changes

2022-03-24 06:58 UTC, merged