[goldfinch] goldfinch-membership and goldifnch-voting-power strategies
snapshot-labs/snapshot-strategies pull request #492
Opened 2022-03-23 18:39 UTC by sanjayprabhu

New strategies for [goldfinch](https://github.com/goldfinch-eng/mono) protocol

Changes proposed in this pull request:
- A goldfinch membership strategy that checks for eligibility via a UID or the goldfinch golist
- A voting power strategy that returns the sum of GFI held, and claimable airdrop tokens

2022-03-24 07:23 UTC, ChaituVR requested changes
Hi @sanjayprabhu  Would be great if you can move goldfinch-voting power strategy to a new PR, It is much easier to review and integrate that way :)

2022-03-24 18:22 UTC, sanjayprabhu commented
@ChaituVR thanks for the feedback. I moved voting-power to https://github.com/snapshot-labs/snapshot-strategies/pull/497

2022-03-24 19:14 UTC, ChaituVR requested changes

2022-03-24 19:14 UTC, ChaituVR commented on src/strategies/goldfinch-membership/index.ts
> +export const author = 'blakewest';
```suggestion
export const author = 'sanjayprabhu';
```

2022-03-24 19:14 UTC, ChaituVR commented on src/strategies/goldfinch-membership/index.ts
> +};
```suggestion
const goListAbi = [ 'function goList(address) view returns (bool)' ]
```

2022-03-24 19:14 UTC, ChaituVR commented on src/strategies/goldfinch-membership/index.ts
> +    [goListAbi],
```suggestion
    goListAbi,
```

2022-03-24 19:14 UTC, ChaituVR commented on src/strategies/goldfinch-membership/index.ts
> +  const strategyFn = _strategies['erc1155-all-balances-of'].strategy;
Would be great if you can change this to import just `erc1155-all-balances-of` strategy into this
```
import strategy as erc1155AllBalancesOf from '../erc1155-all-balances-of';
```

2022-03-24 21:22 UTC, sanjayprabhu commented
Thanks, updated both PRs

2022-03-25 06:50 UTC, ChaituVR commented
Thanks @sanjayprabhu Looks good

2022-03-25 06:50 UTC, ChaituVR approved these changes

2022-03-25 06:50 UTC, merged