[goldfinch-voting-power] Implement goldfinch voting power strategy
snapshot-labs/snapshot-strategies pull request #497
Opened 2022-03-24 18:21 UTC by sanjayprabhu

Voting power strategy for [goldfinch](https://github.com/goldfinch-eng/mono) protocol

See also https://github.com/snapshot-labs/snapshot-strategies/pull/492

Changes proposed in this pull request:
- A voting power strategy that returns the sum of GFI held, and claimable airdrop tokens

2022-03-24 19:15 UTC, ChaituVR requested changes

2022-03-24 19:15 UTC, ChaituVR commented on src/strategies/goldfinch-voting-power/index.ts
> +};
```suggestion
const COMMUNITY_REWARDS_ABI = [ 'function totalUnclaimed(address owner) view returns (uint256)' ];
```


and same changes as in https://github.com/snapshot-labs/snapshot-strategies/pull/492 :)

2022-03-25 06:52 UTC, ChaituVR commented
@sanjayprabhu Can u resolve conflicts, please :) Good to merge

2022-03-25 07:55 UTC, sanjayprabhu commented
Ah yeah, I was afraid of that. Fixed. Thanks for the quick reviews!

2022-03-25 08:05 UTC, ChaituVR approved these changes

2022-03-25 08:05 UTC, merged