[cake] add cake pool subgraph
snapshot-labs/snapshot-strategies pull request #527
Opened 2022-04-08 06:46 UTC by chef-jojo

Changes proposed in this pull request:
- Add cake pool subgraph to add the syrup pools voting power back
- For proposal snapshot < 16300686, add missing master chef and pool balance.

2022-04-11 06:25 UTC, ChaituVR requested changes
Hi @chef-jojo This strategy fails when we pass more addresses (500 addresses)
Try running 
```
npm test --strategy=cake --more=500
```
and also these changes increase the number of requests being sent from a strategy, the requests should not be more than 5, 
https://github.com/snapshot-labs/snapshot-strategies#checklist-for-adding-a-new-strategy

2022-04-11 10:26 UTC, chef-jojo commented
@ChaituVR, merged some calls! We have a if condition in block number
https://github.com/snapshot-labs/snapshot-strategies/blob/91d2cbeb03b914f47180086beeba861828d9bb14/src/strategies/cake/index.ts#L140-L143

snapshot < onChainVPBlockNumber: 5 calls
snapshot >= onChainVPBlockNumber: 3 calls

2022-04-12 06:49 UTC, ChaituVR requested changes

2022-04-12 06:50 UTC, ChaituVR commented on src/strategies/cake/index.ts
> +  );
oh, this is just for else case right. hmmm

2022-04-12 06:50 UTC, ChaituVR commented on src/strategies/cake/index.ts
> +  );
you can ignore this comment then :)

2022-04-12 06:56 UTC, ChaituVR approved these changes

2022-04-12 06:56 UTC, merged