FantomStarter NFT Staker and Owner calls
snapshot-labs/snapshot-strategies pull request #553
Opened 2022-04-18 10:33 UTC by Igoranze

Added FantomStarter Requests for proposals.

- Aks Staker contract if any FS NFT has been staked for the wallet (calculate price of FS tokens)
- Aks Factory if address is owner of FS NFT (calculate price of FS tokens)

2022-04-18 12:44 UTC, ChaituVR requested changes

2022-04-18 12:44 UTC, ChaituVR commented on src/strategies/index.ts
> +  'fantomstarter-owned-nft': fantomStarterOwnedNFT
Hi @Igoranze Please create separate PRs for these two strategies, it will be easy to review/integrate/refer

2022-04-18 18:09 UTC, ChaituVR commented
Hi @Giovann1#4907 doesn't work when we pass more addresses (500)
Try running this in your local:
```
npm test --strategy=fantomstarter-staked-nft --more=500
```
Make sure these are possing:
```
Test strategy "fantomstarter-staked-nft" (with 500 addresses)
    ✕ Should work with 500 addresses (1198 ms)
    ✕ Should take less than 20 sec. to resolve with 500 addresses (2 ms)
```
Error:
```
missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000}
```
This is usually when there is complex code in your contract function than the node limit, can you try to check if there is some other method to get this voting power.

2022-05-03 21:00 UTC, Igoranze commented
Not needed anymore, using contract_call

2022-05-03 21:00 UTC, closed without merging