[aavegotchi-agip] support for gotchiLending
snapshot-labs/snapshot-strategies pull request #574
Opened 2022-05-01 14:06 UTC by candoizo

Changes proposed in this pull request:
- support gotchiLendings, whales

2022-05-02 05:21 UTC, ChaituVR requested changes
@candoizo This fails when i pass 500 addresses ,
```js
TypeError: Cannot read properties of undefined (reading 'map')

      410 |         }
      411 |         for (let i = 0; i < 5; i++) {
    > 412 |             gotchisOwned.push(...result[['gotchiLendings', lowercaseAddr, i * maxResultsPerQuery].join('_')].map(({ gotchi }) => gotchi));
          |                                                                                                              ^
      413 |         }
      414 |         let gotchisBrsEquipValue = 0;
      415 |         if (gotchisOwned.length > 0) {

      at map (dist/strategies/aavegotchi-agip/index.js:412:[110](https://github.com/snapshot-labs/snapshot-strategies/runs/6252585612?check_suite_focus=true#step:3:110))
          at Array.map (<anonymous>)
      at Object.strategy (dist/strategies/aavegotchi-agip/index.js:403:41)
      at callStrategy (dist/utils.js:18:19)
          at async Promise.all (index 0)
      at Object.getScoresDirect (dist/utils.js:29:16)
      at Object.<anonymous> (test/index.spec.ts:153:20)
      
```
Try running this in your local
```bash
      yarn test --strategy=aavegotchi-agip --more=500
```

2022-05-02 17:21 UTC, ChaituVR commented
@candoizo There is an open proposal on aavegotchi space. and this change may affect the proposal voting?

2022-05-02 17:41 UTC, candoizo commented
> ChaituVR

Its alright in this case, there is overwhelming community consensus in favour of having this change implemented as soon as is possible. the author of the open proposal made their own decision to open it prematurely and doesnt object to the change

2022-05-03 16:48 UTC, ChaituVR approved these changes

2022-05-03 16:48 UTC, merged