add citydao strategy
snapshot-labs/snapshot-strategies pull request #575
Opened 2022-05-02 10:41 UTC by RosebuDAO

address must be in proof of humanity registry.
address must hold at least 1 CityDAO Citizen NFT,
granting them a maximum of 1 vote

2022-05-02 10:42 UTC, RosebuDAO commented
haven't tested this strategy at all but seeking feedback. am I even doing it right?

I am trying to find an address that is in PoH registry and owns a Citizen NFT, will force push updating examples.json once I have one

2022-05-02 13:47 UTC, ChaituVR requested changes
```
Error: src/strategies/citydao/index.ts(31,27): error TS2551: Property 'foreach' does not exist on type '[string, number][]'. Did you mean 'forEach'?
Error: src/strategies/citydao/index.ts(38,13): error TS2349: This expression is not callable.
```

2022-05-03 02:58 UTC, RosebuDAO commented
As for testing, Vitalik Buterin is in the POH registry with this address: 0x1db3439a222c519ab44bb1144fc28167b4fa6ee6 and he owns [several erc1155 NFTs](https://etherscan.io/address/0x1db3439a222c519ab44bb1144fc28167b4fa6ee6#tokentxnsErc1155)
here's one: 0x179335e8b0005210c2fa9a1dfb7f92cf636157ad
tokenId: 140

still trying to find a citydao citizen with proof of humanity though

2022-05-04 17:13 UTC, ChaituVR commented
@RosebuDAO 
There are still errors:
```js
src/strategies/citydao/index.ts(38,13): error TS[23](https://github.com/snapshot-labs/snapshot-strategies/runs/6294108347?check_suite_focus=true#step:3:23)49: This expression is not callable.
  Type 'Number' has no call signatures.
error Command failed with exit code 2.
```
Try running this in your local:
```bash
yarn test --strategy=citydao --more=500
```


and for 
> still trying to find a citydao citizen with proof of humanity though

May be try this https://snapshot.org/#/strategy/proof-of-humanity

2022-05-13 12:28 UTC, RosebuDAO commented
I got a test env set up and did some research but can't figure out how to solve that bug. Maybe the code is incorrect in the first place? My experience with JS/TS is minimal.

`const result1: Record<string, number> = await multi1.execute();`

how do I convert this to an object that my strategy can return?

2022-05-15 12:34 UTC, RosebuDAO commented on src/strategies/citydao/index.ts
> +  console.log(votes);
Output of this console.log:
Map(0) {
      '0xf4d895311987faebd839908a0793461087b229c6': 0,
      '0x1db3439a222c519ab44bb1144fc28167b4fa6ee6': 1
    }


Really puzzled why this strategy isn't working at this point. The test suite fails on "Should return an array of object with addresses". It is seeing an empty object where it shouldn't.

2022-05-15 13:17 UTC, RosebuDAO commented on src/strategies/citydao/index.ts
> +  console.log(votes);
it's because I was using votes[address] = balance; .... instead of votes.set(address, balance);

2022-05-15 13:21 UTC, RosebuDAO reviewed
The test suite PASSES now.

2022-05-15 13:21 UTC, RosebuDAO commented on src/strategies/citydao/examples.json
> +        "cityDaoCitizenNftContract": "0x40e27947a914e683089c6925313f782079b6f7f6",
This isn't the CityDAO Citizen NFT it's just some random erc1155 that Vitalik Buterin happens to hold

2022-05-16 06:50 UTC, RosebuDAO commented
@ChaituVR it passes without errors now. sorry for wasting your time with those earlier revisions.

2022-05-17 17:08 UTC, will-holley commented
This strategy is not officially affiliated with CityDAO and **should not imply as such**. Please remove "CityDAO" from its name so that people are not misled.

2022-05-18 06:55 UTC, RosebuDAO commented
> This strategy is not officially affiliated with CityDAO and **should not imply as such**. Please remove "CityDAO" from its name so that people are not misled.

I'm a CityDAO Citizen, same as you. Once it's merged in I intend on creating a proposal to start using it, which would make it official. I'll rename it to citydao-one-human-one-vote as a compromise.

2022-05-18 08:33 UTC, RosebuDAO commented
Yay I finally found an address that's both in the Proof of Humanity registry and owns a CityDAO Citizen NFT! I updated examples.json accordingly. It's this address: 0x99A5A6010e81d3Efa13d5832043E9C3B6c11Ef3d

Rather than wait for this to get merged I'll just propose it as soon as your [QV proposal](https://snapshot.org/#/daocity.eth/proposal/0x03fa9dd24efa6b64f3f05b1b55b794d9c8b2de98ee82f67d196050c7b54c6bca) ends, May 23rd :). That would make it "official".

2022-05-18 13:37 UTC, RosebuDAO commented
You're right I may have jumped the gun, so I went ahead and started the [Proposal on CityDAO's forum](https://forum.citydao.io/t/cip-60-one-human-one-vote/1408)... since it might take a while to get "20 likes" before it goes up for official voting on Snapshot.

Let's just leave this PR right here in this state until the vote happens.

> The voting strategy that you're proposing has not been commissioned, audited, tested...

Bug reports and patches welcomed.

2022-06-11 16:33 UTC, ChaituVR commented
Closing this as stale, feel free to reopen if needed

2022-06-11 16:33 UTC, closed without merging