Add strategy for ENS 10k Club
snapshot-labs/snapshot-strategies pull request #607
Opened 2022-05-18 19:26 UTC by paste

This strategy is for 10K Club members, holders of 000-9999 ENS names. I needed to hardcode token IDs because the list is too long to pass through snapshot UI. This script queries TheGraph for all ENS names owned by voter and checks them against list of 10K Club token IDs. 999 Club voters get weighted 10x by default.

2022-05-20 17:41 UTC, ChaituVR requested changes

2022-05-20 17:41 UTC, ChaituVR commented on src/strategies/ens-10k-club/index.ts
> +import { TOKEN_IDS_10K_CLUB } from './10k-club-token-ids';
Hey, what are these ids? these should not be on this repo., maybe should be on an IPFS file and fetch it when required

2022-06-03 23:59 UTC, paste commented
Hi @ChaituVR, rewritten and much simpler. I apologize for the attitude!

2022-06-05 04:33 UTC, ChaituVR approved these changes
Thanks for the changes @paste Its ok i can understand :) 

I feel like we can do like `parseInt(labelName)` something like that, but not sure if it is possible. Maybe you can try it for next version, merging this for now as this looks good

2022-06-05 04:33 UTC, merged