[sunrisegaming-univ2-lp] Add sunrisegaming-univ2-lp strategie
snapshot-labs/snapshot-strategies pull request #61
Opened 2021-09-16 06:39 UTC by sunrisedao

Add sunrisegaming-univ2-lp strategie

- Balances of the underlying token in LP swap and staking pool

2021-09-16 06:46 UTC, ChaituVR requested changes

2021-09-16 06:46 UTC, ChaituVR commented on src/strategies/sunrisegaming-univ2-lp/index.ts
> +];
```suggestion
const erc20Abi = [
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)'
];
```

2021-09-16 06:46 UTC, ChaituVR commented on src/strategies/sunrisegaming-univ2-lp/index.ts
> +];
```suggestion
const masterChefAbi = [
  'function userInfo(uint256, address) view returns (uint256 amount, uint256 rewardDebt)',
  'function poolInfo(uint256) view returns (address lpToken, uint256 allocPoint, uint256 lastRewardBlock, uint256 accMMPerShare, uint256 amount)'
];
```

2021-09-16 06:46 UTC, ChaituVR commented on src/strategies/sunrisegaming-univ2-lp/index.ts
> +export const author = 'sunrisegaming';
should be a github username
```suggestion
export const author = 'sunrisedao';
```

2021-09-16 06:58 UTC, sunrisedao commented
@ChaituVR I've updated the source code

2021-09-16 09:42 UTC, bonustrack approved these changes

2021-09-16 12:18 UTC, ChaituVR approved these changes

2021-09-16 12:19 UTC, ChaituVR requested changes
Plz fix conflicts, we should be good to go :)

2021-09-16 17:21 UTC, ChaituVR commented
@sunrisedao something went wrong with this PR, i see changes in 10 files :/ can u check, thanks

2021-09-17 03:10 UTC, sunrisedao commented
@ChaituVR I've the new one https://github.com/snapshot-labs/snapshot-strategies/pull/65

2021-09-17 03:10 UTC, closed without merging