Added the Rowdy Roos voting strategy
snapshot-labs/snapshot-strategies pull request #616
Opened 2022-05-26 20:30 UTC by npbroo

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2022-05-27 11:30 UTC, ChaituVR requested changes
Plz revert changes from package-lock and yarn.lock

2022-05-27 15:40 UTC, npbroo commented
I have reverted the changes for yarn.lock and package-lock.json please review. Thank you

2022-05-28 07:56 UTC, ChaituVR requested changes

2022-05-28 07:56 UTC, ChaituVR commented on src/strategies/rowdy-roos/index.ts
> +export const author = 'Kanga';
```suggestion
export const author = 'npbroo';
```

2022-05-28 07:56 UTC, ChaituVR commented on src/strategies/rowdy-roos/index.ts
> +  await addresses.forEach((address) => {
```suggestion
  addresses.forEach((address) => {
```

2022-05-28 07:56 UTC, ChaituVR commented on src/strategies/rowdy-roos/index.ts
> +  ] = await Promise.all([stakingPool.execute()]);
```suggestion
  const stakedRewardsResponse: Record<string, BigNumberish[]> = await stakingPool.execute();
```

2022-05-28 07:56 UTC, ChaituVR commented on src/strategies/rowdy-roos/index.ts
> +        total_staked_reward+=parseInt(formatUnits(BigNumber.from(stakedRewardsResponse[id]), options.decimals))
```suggestion
        total_staked_reward += parseInt(formatUnits(BigNumber.from(stakedRewardsResponse[id]), options.decimals))
```

2022-05-28 18:08 UTC, ChaituVR approved these changes

2022-05-28 18:08 UTC, merged