[Version 0.0.1] ethermon-erc721
snapshot-labs/snapshot-strategies pull request #620
Opened 2022-05-29 15:41 UTC by syedMohib44

Fixes # .

Initial commit.

2022-05-29 15:42 UTC, syedMohib44 commented
[Version 0.0.1] ethermon-erc721

2022-05-30 08:11 UTC, ChaituVR requested changes

2022-05-30 08:11 UTC, ChaituVR commented on src/strategies/ethermon-erc721/index.ts
> +export const author = 'mariana44';
```suggestion
export const author = 'syedMohib44';
```

2022-05-30 08:11 UTC, ChaituVR commented on src/strategies/ethermon-erc721/README.md
> +# ethermon-erc721
Please revert changes from the package-lock file

2022-05-30 08:11 UTC, ChaituVR commented on test/index.spec.ts
> +    it(`Should take less than 20 sec. to resolve with ${moreArg || 500
Please revert changes from this spec file

2022-05-30 08:11 UTC, ChaituVR commented on test/delegation.ts
> +const addresses = ['0x038ae33f4bbfd9e0489abd7e622f014244433f72'];
Also revert this plz

2022-05-30 08:11 UTC, ChaituVR commented on src/strategies/ethermon-erc721/examples.json
> +        "classIdWeight": {
It is not good idea to store all these weights inside strategy params, maybe you can store these in a IPFS file and fetch it when required?

2022-05-30 09:28 UTC, syedMohib44 reviewed
Changes resolved

2022-05-30 09:38 UTC, syedMohib44 reviewed
Resolved name changed

2022-05-30 12:46 UTC, ChaituVR requested changes
@syedMohib44 Still see changes in package-lock and also need to move weights in examples.json to IPFS

2022-05-30 14:56 UTC, syedMohib44 commented
> @syedMohib44 Still see changes in package-lock and also need to move weights in examples.json to IPFS

Alright @ChaituVR on it

2022-05-31 02:52 UTC, syedMohib44 commented
@ChaituVR can you verify the changes once. Thanks

2022-06-01 01:09 UTC, syedMohib44 commented
> Hey @syedMohib44 Thanks for the changes, looks good , except that import `ethermon-erc721` strategy into src/strategies/index.ts like other strategies, Thanks

Hii @ChaituVR imported the ethermon-erc721 stragtegy in index.ts can please review it once. Thanks you.

2022-06-01 07:09 UTC, syedMohib44 commented
> @syedMohib44 IPFS file doesn't resolve well, Is it pinned correctly? make sure to use a third-party provider like pinata or fleek
> 
> Or is there any other way to get these weights on chain? maybe from subgraph?

@ChaituVR there is a problem with IPFS I guess 😄 previously it was pinned and not working that 504 gateway problem then I unpinned it and worked not sure what was the issue but ipfs is not reliable can do test now and let us know. Will update this to some reliable solution in next version.

2022-06-01 09:26 UTC, syedMohib44 commented
> Hey @syedMohib44 Thanks for the changes, looks good , except that import `ethermon-erc721` strategy into src/strategies/index.ts like other strategies, Thanks

@ChaituVR all looks good please view import of ethermon-erc721 once would be awesome.

2022-06-02 08:23 UTC, ChaituVR approved these changes

2022-06-02 08:23 UTC, merged