add vs-balance [eth-balance]
snapshot-labs/snapshot-strategies pull request #634
Opened 2022-06-06 14:15 UTC by vchain007

vs decimal get from smartcontract is 6 on vision
- 
- 
-

2022-06-06 18:20 UTC, ChaituVR commented
Vs is like eth? Default on vision chain?

I think better to modify  eth-balance strategy itself, try passing a optional parameter decimals and default value as 18

2022-06-07 01:54 UTC, vchain007 commented
> Vs is like eth? Default on vision chain?
> 
> I think better to modify eth-balance strategy itself, try passing a optional parameter decimals and default value as 18
yes , vs is native token on vision chain .but it's dicimal is 6  . we adapter eth_getbalance interface so this interface return 
dicimal 18 . For example
user A have 1000 VS , on vision chain A have 1000*10e6 . eth_getbalance return 1000* 10e18 just for adaptering .multicall query smart contract return 1000*10e6

2022-06-07 02:48 UTC, vchain007 commented
update . plz review

2022-06-07 18:14 UTC, ChaituVR requested changes

2022-06-07 18:14 UTC, ChaituVR commented on src/strategies/eth-balance/index.ts
> +  const decimals = decimals in options ? options.decimals : 18 ;
```suggestion
  const decimals = options.decimals || 18 ;
```

2022-06-07 18:20 UTC, merged

2022-06-08 00:40 UTC, vchain007 commented
when will this strategy effect online ,sir