Implemented erc721-with-metadata-simple strategy
snapshot-labs/snapshot-strategies pull request #645
Opened 2022-06-10 02:46 UTC by victor-kyriazakos

Changes proposed in this pull request:

Added "erc721-with-metadata-simple" strategy
Similar to "erc721-tokenid-range-weights-simple", it does not require the erc721Enumerable extension
Does not use "tokenOfOwnerByIndex" contract method

2022-06-10 07:25 UTC, ChaituVR requested changes
Hi @victor-kyriazakos What's the difference between this strategy and https://snapshot.org/#/strategy/erc721-with-metadata strategy? 

Also revert all the changes from other files than your new strategies including package-lock and yarn.lock

2022-06-10 12:24 UTC, victor-kyriazakos commented
Hi @ChaituVR I reverted the changes you asked for.

As described in the original description, the difference with "erc721-with-metadata" is that it doesn't require the contract to implement the ERC721Enumerable interface by OpenZeppeling, similar to the difference between "erc721-with-tokenid-range-weights" and "erc721-with-tokenid-range-weights-simple". It does not use the "tokenOfOwnerByIndex" contract method

2022-06-11 16:35 UTC, ChaituVR requested changes
```/home/runner/work/snapshot-strategies/snapshot-strategies/src/strategies/erc721-with-metadata-simple/index.ts
Error:   17:9  error  'ids' is never reassigned. Use 'const' instead  prefer-const```

2022-06-12 08:02 UTC, ChaituVR requested changes
Hi @victor-kyriazakos The name doesn't match the strategy, it is def. not as `simple` as the existing strategy 😅 Can you think of a different name? maybe like `erc721-with-metadata-by-ownerof`?

2022-06-14 16:29 UTC, victor-kyriazakos commented on src/strategies/erc721-with-metadata-simple/index.ts
> +  'function balanceOf(address account) external view returns (uint256)',
Correct, not used - removed

2022-06-14 16:30 UTC, victor-kyriazakos commented on src/strategies/erc721-with-metadata-simple/index.ts
> +  const maximumAllowedRange = maximumNumberOfBatches * batchSize;
Defined the maxAllowedRange to 8000 * 4 = 32000 directly. Let me know if you meant something different here

2022-06-14 16:32 UTC, victor-kyriazakos commented
Hi @ChaituVR I changed the strategy name to your suggestion - `erc721-with-metadata-by-ownerof` . I think the `-simple` reflected that it works for "simple erc721 contracts" that do not implement the full IEnumerable interface, but your suggested name works just fine :D

2022-06-14 17:44 UTC, ChaituVR commented on src/strategies/erc721-with-metadata-by-ownerof/index.ts
> +    const customRangeResponseWeighted = await multiplyOccurrencesByWeights(
```suggestion
    const customRangeResponseWeighted = multiplyOccurrencesByWeights(
```

2022-06-14 17:47 UTC, ChaituVR commented on src/strategies/erc721-with-metadata-by-ownerof/index.ts
> +  const multiplyOccurrencesByWeights = async (
```suggestion
  const multiplyOccurrencesByWeights = (
```

2022-06-14 17:50 UTC, ChaituVR approved these changes

2022-06-14 17:50 UTC, merged