Update existing strategy with the upcoming election values and create a non-weighted version
snapshot-labs/snapshot-strategies pull request #67
Opened 2021-09-18 07:23 UTC by andytcf

2021-09-18 08:33 UTC, bonustrack reviewed
For the strategy `synthetix-non-quadratic` it should be added here: https://github.com/snapshot-labs/snapshot-strategies/blob/41c8202393c024ab05b86224af19c98dcfcbb169/src/strategies/index.ts

For the strategy `synthetix` is there some breaking changes? The strategy will run on previous proposals too, you may not want previous proposals to break or give different results.

2021-09-19 13:20 UTC, ChaituVR requested changes
Hi @andytcf I see both the strategies are the same except having
```
 Math.sqrt(scaledWeighting);
```
Maybe you can have a helper like [this](https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/uniswap-v3/helper.ts) and use common code in both strategies, it can help reduce the duplicate code

2021-09-20 08:21 UTC, bonustrack approved these changes

2021-09-20 08:32 UTC, ChaituVR approved these changes

2021-09-20 08:32 UTC, merged

2021-09-20 08:54 UTC, ChaituVR commented
new strategies live here:
https://snapshot.org/#/strategy/synthetix-quadratic
https://snapshot.org/#/strategy/synthetix-non-quadratic