Unipilot token balance
snapshot-labs/snapshot-strategies pull request #678
Opened 2022-06-28 11:17 UTC by RAFAQAT11

Fixes # .

Changes proposed in this pull request:
- with this pull request unipilot user will be able to vote regardless of their tokens are staked.

2022-06-28 18:44 UTC, ChaituVR requested changes
Hi @RAFAQAT11 I feel like you can use two `contract-call` strategies here https://snapshot.org/#/strategy/contract-call

2022-06-28 18:44 UTC, ChaituVR commented on src/strategies/index.ts
> +    erc721WithTokenIdRangeWeightsSimple,
```suggestion
'erc721-with-tokenid-range-weights-simple': erc721WithTokenIdRangeWeightsSimple,
```

2022-06-28 18:44 UTC, ChaituVR commented on src/strategies/index.ts
> +    unstackedToadzAndStackedToadzStakers,
```suggestion
  'unstackedtoadz-and-stackedtoadz-stakers': unstackedToadzAndStackedToadzStakers,
```

2022-06-28 18:44 UTC, ChaituVR commented on src/strategies/unipilot-token-balance/index.ts
> +];
```suggestion
const abi_pilot_staking = [
  'function userInfo(address) view returns (uint256 lastUpdateRewardToken, uint256 amount, uint256 rewardDebt)'
];
```

2022-06-29 11:12 UTC, RAFAQAT11 commented
Hi @ChaituVR , suggested things has been implemented. Thanks.

2022-07-02 11:38 UTC, closed without merging