Code cleanup on [xrook-balance-of-underlying-weighted] and [bancor-pool-token-underlying-balance] strategies
snapshot-labs/snapshot-strategies pull request #739
Opened 2022-07-26 14:46 UTC by TudorSante

Fixes # .

Changes proposed in this pull request:
- Performed some code cleanup on [xrook-balance-of-underlying-weighted] and [bancor-pool-token-underlying-balance] strategies

2022-07-27 15:51 UTC, ChaituVR requested changes

2022-07-27 15:52 UTC, ChaituVR commented on src/strategies/index.ts
> -  'crucible-erc20-token-and-lp-weighted': crucibleERC20TokenAndLpWeighted,
Make sure this file is not changed

2022-07-27 18:27 UTC, TudorSante commented on src/strategies/bancor-pool-token-underlying-balance/index.ts
> +    ])
Yea, received some lint fixes on a strategy and wanted to add them everywhere. Also I'm getting familiar to using Git, so sorry if some things are off-track. Gonna implement the above asap

2022-07-27 19:00 UTC, TudorSante commented on src/strategies/bancor-pool-token-underlying-balance/examples.json
> +    "snapshot": "latest"
Done

2022-07-27 19:02 UTC, TudorSante commented on src/strategies/index.ts
> -  'crucible-erc20-token-and-lp-weighted': crucibleERC20TokenAndLpWeighted,
Hopefully this problem was solved

2022-07-28 18:46 UTC, ChaituVR commented
@TudorSante These changes are just lint related and our lint runner already fixed these, and these changes make it bad, so closing it for now,  feel free to reopen if there is a change not related to lint :)

2022-07-28 18:46 UTC, closed without merging