added flexible voucher strategies
snapshot-labs/snapshot-strategies pull request #740
Opened 2022-07-27 09:16 UTC by buchaoqun

Fixes # .

Changes proposed in this pull request:
- added flexible voucher strategies
- erc3525 vesting voucher change amount value
-

2022-07-27 09:30 UTC, bonustrack commented
@buchaoqun Can you add a readme for the strategy? Curious to know how it works, is it some kind of pay to vote system?

2022-07-28 09:41 UTC, buchaoqun commented
> @buchaoqun Can you add a readme for the strategy? Curious to know how it works, is it some kind of pay to vote system?

Thank you for your attention to the our proposal based on ERC3525. Please allow me to explain in response to your question.
The strategy you see is based on ERC3525, a new asset standard. You can think of ERC3525 as an NFT, and Vesting Voucher is a new asset which encapsulated ERC20 tokens in the voucher.
Therefore, when users hold ERC3525, they are able to gain the corresponding governance power or weighs up the governance right as the time goes by, just like Curve's veCRV. 
This is not a pay to vote system.
The ERC3525 is mainly adopted by SolvProtocol and FuJiDAO, and there are more than 40 projects using ERC3525 (DoDo, Cls, HighStreat, USF, etc.) to lock their tokens.
So we need strategies like this to engage with our voucher holders. Thank you

2022-07-28 09:54 UTC, bonustrack commented
Sound great thanks for the details!

2022-07-29 13:19 UTC, ChaituVR requested changes

2022-07-29 13:19 UTC, ChaituVR commented on src/strategies/erc3525-vesting-voucher/index.ts
> +        const address = walletID.split('-')[0];
@buchaoqun Looks like it is messing up lint in this file

2022-08-02 11:45 UTC, ChaituVR requested changes

2022-08-02 11:45 UTC, ChaituVR commented on src/strategies/erc3525-vesting-voucher/index.ts
>  ) {
@buchaoqun make sure it is not changing other strategies, revert changes from these files plz :)

2022-08-03 05:40 UTC, ChaituVR commented
@buchaoqun I still see many changes in other strategy where the lint is messed up, try going here, https://github.com/snapshot-labs/snapshot-strategies/pull/740/files make sure it contains changes from your strategy

2022-08-03 06:22 UTC, buchaoqun reviewed
done

2022-08-04 09:01 UTC, buchaoqun reviewed
@ChaituVR done

2022-08-04 10:46 UTC, ChaituVR approved these changes

2022-08-04 10:46 UTC, merged