Add files via upload
snapshot-labs/snapshot-strategies pull request #789
Opened 2022-08-22 13:51 UTC by blocksworkz

Fixes # .

Changes proposed in this pull request:
- 
- Added the BLKZ custom strategy
-

2022-08-22 13:52 UTC, blocksworkz commented
Adding in a new custom strategy for the XDC network (BLKZ)

2022-08-22 17:29 UTC, ChaituVR requested changes

2022-08-22 17:29 UTC, ChaituVR commented on src/strategies/xrc20-balance-of-blkz/index.ts
> +  );
Hey @blocksworkz You can use `erc20-balance-of` on your space with your network right? why do we need a new strategy?

2022-09-19 17:22 UTC, ChaituVR commented
Closing this as stale. feel free to reopen if needed

2022-09-19 17:22 UTC, closed without merging