tpro-staking v1.0.0
snapshot-labs/snapshot-strategies pull request #798
Opened 2022-08-24 11:04 UTC by AdrianKochanski

New strategy # .

2022-08-24 12:19 UTC, ChaituVR requested changes

2022-08-24 12:19 UTC, ChaituVR commented on src/strategies/tpro-staking/index.ts
> +];
```suggestion
const abi = [
  'function userInfo(uint256, address) view returns (uint256 amount, uint256 rewardDebt, uint256 pendingRewards, uint256 lockedTimestamp, uint256 lockupTimestamp, uint256 lockupTimerange, uint256 virtAmount)'
];
```

2022-08-25 07:43 UTC, AdrianKochanski commented
@ChaituVR PR is ready

2022-08-25 13:17 UTC, ChaituVR approved these changes

2022-08-25 13:17 UTC, merged