Add sunder strategies
snapshot-labs/snapshot-strategies pull request #8
Opened 2021-08-05 02:30 UTC by krotos-arch

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2021-08-05 09:05 UTC, krotos-arch reviewed
Update example json

2021-08-06 15:38 UTC, ChaituVR requested changes

2021-08-06 15:38 UTC, ChaituVR commented on src/strategies/sunder/index.ts
> +export const author = 'aaron';
```suggestion
export const author = 'krotos-arch';
```

2021-08-06 15:39 UTC, ChaituVR requested changes
@krotos-arch There is some error:
```
  ● 
Test strategy "sunder" › Strategy should run without any errors

    call revert exception (method="aggregate((address,bytes)[])", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)

      at Logger.Object.<anonymous>.Logger.makeError (node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.Object.<anonymous>.Logger.throwError (node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at Interface.Object.<anonymous>.Interface.decodeFunctionResult (node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:384:23)
      at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:291:44)
      at step (node_modules/@ethersproject/contracts/lib/index.js:46:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:27:53)
      at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:18:58)
```

2021-08-07 16:51 UTC, ChaituVR commented
@krotos-arch Hey, I think the error is because your fork branch is outdated from the master branch (many big changes pushed recently), can you please update your branch with those, that should fix this weird issue :)

2021-08-14 10:13 UTC, closed without merging