Otterspace badges
snapshot-labs/snapshot-strategies pull request #808
Opened 2022-08-31 11:38 UTC by rahulrumalla

Fixes # .

Changes proposed in this pull request:
- Works with Goerli
- Adding a new strategy for using Otterspace badges (based on ERC4973, non-transferable tokens)

Will follow up with Optimism network once all end-to-end testing on goerli is verified.

2022-08-31 18:09 UTC, ChaituVR requested changes
Hey @rahulrumalla 👋 Looks like some tests are failing (not returning any positive voting power) can you check by running this strategy locally? try running: `yarn test --strategy=otterspace-badges`

2022-09-01 08:38 UTC, rahulrumalla commented
Ah! Had a change upstream in subgraph. Fixed and resolve merge conflict as well.

2022-09-01 11:28 UTC, ChaituVR approved these changes

2022-09-01 11:33 UTC, ChaituVR commented on src/strategies/otterspace-badges/index.ts
> +export const author = 'otterspace';
```suggestion
export const author = 'otterspace-xyz';
```

2022-09-01 11:34 UTC, ChaituVR commented on src/strategies/otterspace-badges/index.ts
> +export const author = 'otterspace';
I forgot about this @rahulrumalla should be your GitHub id or org's GitHub id

2022-09-01 11:34 UTC, ChaituVR requested changes
GitHub id missing

2022-09-01 13:11 UTC, ChaituVR approved these changes

2022-09-01 13:11 UTC, merged