:sparkles: [streategy ]Adding the ethalend strategy
snapshot-labs/snapshot-strategies pull request #825
Opened 2022-09-08 11:49 UTC by guillermoriv

Fixes # .

Changes proposed in this pull request:
- Adding the strategy to fetchBalances for smartWallet in ETHALend Protocol (polygon)
- Link to the protocol: https://www.ethalend.org/

2022-09-09 06:50 UTC, ChaituVR requested changes
Hey @guillermoriv Can you remove addresses from examples.json? ideally it should be less 😄 maybe 10 addresses should be fine

2022-09-09 08:03 UTC, guillermoriv commented
Yes of course @ChaituVR, I will do that asap, thanks for the quick answer !

2022-09-09 08:08 UTC, guillermoriv commented
It should be fine now, I'll request your review again @ChaituVR, thanks.

2022-09-13 17:27 UTC, ChaituVR approved these changes

2022-09-13 17:27 UTC, merged