Introduce ninechronicles-staked-and-dcc
snapshot-labs/snapshot-strategies pull request #901
Opened 2022-10-24 14:56 UTC by longfin

This PR adds a new strategy using [Nine Chronicles]'s staked assets.

- Since Nine Chronicles has its own mainnet other than Ethereum or other evm-compact chains, it needs some GrpahQL requests, and a block hash as a parameter to specify the point of snapshot time on that chain. [^1]
- I'm pretty new to snapshot strategies. so, there may be wrong codes or additional corrections to be made. please let me know.

[Nine Chronicles]: https://nine-chronicles.com/

[^1]: I also think it's a little bit weird and I might revise this version with a snapshot mapper in near future. :sweat_smile:

2022-10-24 18:39 UTC, ChaituVR requested changes

2022-10-24 18:39 UTC, ChaituVR commented on src/strategies/ninechronicles-staked-and-dcc/index.ts
> +
```suggestion
export const dependOnOtherAddress = false;

```

2022-10-24 18:39 UTC, ChaituVR commented on src/strategies/ninechronicles-staked-and-dcc/index.ts
> +  addresses.map(formatEthAddress);
```suggestion
  addresses = addresses.map(formatEthAddress);
```

2022-10-25 06:25 UTC, longfin commented
@ChaituVR Thanks for the fixings! I updated this branch by merging. PTAL.

2022-10-25 08:27 UTC, ChaituVR approved these changes

2022-10-25 08:27 UTC, merged