POAP Fixes
snapshot-labs/snapshot-strategies pull request #988
Opened 2022-12-13 22:02 UTC by gawainb

Fixes #977 and #867 .

Changes proposed in this pull request:

- 1:1 strategy should also be capable of only counting specific tokens per their event id
- will use the erc721 strategy if no event ids passed
- with-weight block/snapshot param may not have been returning expected results

2022-12-15 08:22 UTC, ChaituVR requested changes

2022-12-15 08:23 UTC, ChaituVR commented on src/strategies/poap-with-weight/index.ts
> +    getTokenSupply.tokens.__args['block'] = { number: snapshot };
```suggestion
    getTokenSupply.tokens.__args.block = { number: snapshot };
```

2022-12-15 08:23 UTC, ChaituVR commented on src/strategies/poap-with-weight/index.ts
> +export const version = '1.2.0';
```suggestion
export const version = '1.1.0';
```

2022-12-16 20:26 UTC, gawainb commented on src/strategies/poap-with-weight/index.ts
> -    getTokenSupply.tokens.__args.block = { number: snapshot };
@greenealexander looks like this is ok the way it is 🙂

2022-12-17 00:42 UTC, greenealexander commented on src/strategies/poap-with-weight/index.ts
> -    getTokenSupply.tokens.__args.block = { number: snapshot };
@gawainb yeah, this can be reverted

2022-12-27 14:39 UTC, ChaituVR approved these changes

2022-12-27 14:40 UTC, merged